// Code generated by ent, DO NOT EDIT.

package learningprogress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldUserID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldItemID, v))
}

// ReflectionEncrypted applies equality check predicate on the "reflection_encrypted" field. It's identical to ReflectionEncryptedEQ.
func ReflectionEncrypted(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldReflectionEncrypted, v))
}

// OutcomeEncrypted applies equality check predicate on the "outcome_encrypted" field. It's identical to OutcomeEncryptedEQ.
func OutcomeEncrypted(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldOutcomeEncrypted, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContainsFold(FieldUserID, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldItemID, v))
}

// ItemIDContains applies the Contains predicate on the "item_id" field.
func ItemIDContains(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContains(FieldItemID, v))
}

// ItemIDHasPrefix applies the HasPrefix predicate on the "item_id" field.
func ItemIDHasPrefix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasPrefix(FieldItemID, v))
}

// ItemIDHasSuffix applies the HasSuffix predicate on the "item_id" field.
func ItemIDHasSuffix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasSuffix(FieldItemID, v))
}

// ItemIDEqualFold applies the EqualFold predicate on the "item_id" field.
func ItemIDEqualFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEqualFold(FieldItemID, v))
}

// ItemIDContainsFold applies the ContainsFold predicate on the "item_id" field.
func ItemIDContainsFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContainsFold(FieldItemID, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldState, vs...))
}

// ReflectionEncryptedEQ applies the EQ predicate on the "reflection_encrypted" field.
func ReflectionEncryptedEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedNEQ applies the NEQ predicate on the "reflection_encrypted" field.
func ReflectionEncryptedNEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedIn applies the In predicate on the "reflection_encrypted" field.
func ReflectionEncryptedIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldReflectionEncrypted, vs...))
}

// ReflectionEncryptedNotIn applies the NotIn predicate on the "reflection_encrypted" field.
func ReflectionEncryptedNotIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldReflectionEncrypted, vs...))
}

// ReflectionEncryptedGT applies the GT predicate on the "reflection_encrypted" field.
func ReflectionEncryptedGT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedGTE applies the GTE predicate on the "reflection_encrypted" field.
func ReflectionEncryptedGTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedLT applies the LT predicate on the "reflection_encrypted" field.
func ReflectionEncryptedLT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedLTE applies the LTE predicate on the "reflection_encrypted" field.
func ReflectionEncryptedLTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedContains applies the Contains predicate on the "reflection_encrypted" field.
func ReflectionEncryptedContains(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContains(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedHasPrefix applies the HasPrefix predicate on the "reflection_encrypted" field.
func ReflectionEncryptedHasPrefix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasPrefix(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedHasSuffix applies the HasSuffix predicate on the "reflection_encrypted" field.
func ReflectionEncryptedHasSuffix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasSuffix(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedIsNil applies the IsNil predicate on the "reflection_encrypted" field.
func ReflectionEncryptedIsNil() predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIsNull(FieldReflectionEncrypted))
}

// ReflectionEncryptedNotNil applies the NotNil predicate on the "reflection_encrypted" field.
func ReflectionEncryptedNotNil() predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotNull(FieldReflectionEncrypted))
}

// ReflectionEncryptedEqualFold applies the EqualFold predicate on the "reflection_encrypted" field.
func ReflectionEncryptedEqualFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEqualFold(FieldReflectionEncrypted, v))
}

// ReflectionEncryptedContainsFold applies the ContainsFold predicate on the "reflection_encrypted" field.
func ReflectionEncryptedContainsFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContainsFold(FieldReflectionEncrypted, v))
}

// OutcomeEncryptedEQ applies the EQ predicate on the "outcome_encrypted" field.
func OutcomeEncryptedEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedNEQ applies the NEQ predicate on the "outcome_encrypted" field.
func OutcomeEncryptedNEQ(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedIn applies the In predicate on the "outcome_encrypted" field.
func OutcomeEncryptedIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldOutcomeEncrypted, vs...))
}

// OutcomeEncryptedNotIn applies the NotIn predicate on the "outcome_encrypted" field.
func OutcomeEncryptedNotIn(vs ...string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldOutcomeEncrypted, vs...))
}

// OutcomeEncryptedGT applies the GT predicate on the "outcome_encrypted" field.
func OutcomeEncryptedGT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedGTE applies the GTE predicate on the "outcome_encrypted" field.
func OutcomeEncryptedGTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedLT applies the LT predicate on the "outcome_encrypted" field.
func OutcomeEncryptedLT(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedLTE applies the LTE predicate on the "outcome_encrypted" field.
func OutcomeEncryptedLTE(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedContains applies the Contains predicate on the "outcome_encrypted" field.
func OutcomeEncryptedContains(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContains(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedHasPrefix applies the HasPrefix predicate on the "outcome_encrypted" field.
func OutcomeEncryptedHasPrefix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasPrefix(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedHasSuffix applies the HasSuffix predicate on the "outcome_encrypted" field.
func OutcomeEncryptedHasSuffix(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldHasSuffix(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedIsNil applies the IsNil predicate on the "outcome_encrypted" field.
func OutcomeEncryptedIsNil() predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIsNull(FieldOutcomeEncrypted))
}

// OutcomeEncryptedNotNil applies the NotNil predicate on the "outcome_encrypted" field.
func OutcomeEncryptedNotNil() predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotNull(FieldOutcomeEncrypted))
}

// OutcomeEncryptedEqualFold applies the EqualFold predicate on the "outcome_encrypted" field.
func OutcomeEncryptedEqualFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEqualFold(FieldOutcomeEncrypted, v))
}

// OutcomeEncryptedContainsFold applies the ContainsFold predicate on the "outcome_encrypted" field.
func OutcomeEncryptedContainsFold(v string) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldContainsFold(FieldOutcomeEncrypted, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LearningProgress {
	return predicate.LearningProgress(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LearningProgress) predicate.LearningProgress {
	return predicate.LearningProgress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LearningProgress) predicate.LearningProgress {
	return predicate.LearningProgress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LearningProgress) predicate.LearningProgress {
	return predicate.LearningProgress(sql.NotPredicates(p))
}
