// Code generated by ent, DO NOT EDIT.

package supportactionaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContainsFold(FieldID, id))
}

// SupportCaseID applies equality check predicate on the "support_case_id" field. It's identical to SupportCaseIDEQ.
func SupportCaseID(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldSupportCaseID, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldOperatorID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldAction, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// SupportCaseIDEQ applies the EQ predicate on the "support_case_id" field.
func SupportCaseIDEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldSupportCaseID, v))
}

// SupportCaseIDNEQ applies the NEQ predicate on the "support_case_id" field.
func SupportCaseIDNEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNEQ(FieldSupportCaseID, v))
}

// SupportCaseIDIn applies the In predicate on the "support_case_id" field.
func SupportCaseIDIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIn(FieldSupportCaseID, vs...))
}

// SupportCaseIDNotIn applies the NotIn predicate on the "support_case_id" field.
func SupportCaseIDNotIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotIn(FieldSupportCaseID, vs...))
}

// SupportCaseIDGT applies the GT predicate on the "support_case_id" field.
func SupportCaseIDGT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGT(FieldSupportCaseID, v))
}

// SupportCaseIDGTE applies the GTE predicate on the "support_case_id" field.
func SupportCaseIDGTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGTE(FieldSupportCaseID, v))
}

// SupportCaseIDLT applies the LT predicate on the "support_case_id" field.
func SupportCaseIDLT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLT(FieldSupportCaseID, v))
}

// SupportCaseIDLTE applies the LTE predicate on the "support_case_id" field.
func SupportCaseIDLTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLTE(FieldSupportCaseID, v))
}

// SupportCaseIDContains applies the Contains predicate on the "support_case_id" field.
func SupportCaseIDContains(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContains(FieldSupportCaseID, v))
}

// SupportCaseIDHasPrefix applies the HasPrefix predicate on the "support_case_id" field.
func SupportCaseIDHasPrefix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasPrefix(FieldSupportCaseID, v))
}

// SupportCaseIDHasSuffix applies the HasSuffix predicate on the "support_case_id" field.
func SupportCaseIDHasSuffix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasSuffix(FieldSupportCaseID, v))
}

// SupportCaseIDEqualFold applies the EqualFold predicate on the "support_case_id" field.
func SupportCaseIDEqualFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEqualFold(FieldSupportCaseID, v))
}

// SupportCaseIDContainsFold applies the ContainsFold predicate on the "support_case_id" field.
func SupportCaseIDContainsFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContainsFold(FieldSupportCaseID, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorIDContains applies the Contains predicate on the "operator_id" field.
func OperatorIDContains(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContains(FieldOperatorID, v))
}

// OperatorIDHasPrefix applies the HasPrefix predicate on the "operator_id" field.
func OperatorIDHasPrefix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasPrefix(FieldOperatorID, v))
}

// OperatorIDHasSuffix applies the HasSuffix predicate on the "operator_id" field.
func OperatorIDHasSuffix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasSuffix(FieldOperatorID, v))
}

// OperatorIDEqualFold applies the EqualFold predicate on the "operator_id" field.
func OperatorIDEqualFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEqualFold(FieldOperatorID, v))
}

// OperatorIDContainsFold applies the ContainsFold predicate on the "operator_id" field.
func OperatorIDContainsFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContainsFold(FieldOperatorID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContainsFold(FieldAction, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldContainsFold(FieldReason, v))
}

// BeforeJSONIsNil applies the IsNil predicate on the "before_json" field.
func BeforeJSONIsNil() predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIsNull(FieldBeforeJSON))
}

// BeforeJSONNotNil applies the NotNil predicate on the "before_json" field.
func BeforeJSONNotNil() predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotNull(FieldBeforeJSON))
}

// AfterJSONIsNil applies the IsNil predicate on the "after_json" field.
func AfterJSONIsNil() predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIsNull(FieldAfterJSON))
}

// AfterJSONNotNil applies the NotNil predicate on the "after_json" field.
func AfterJSONNotNil() predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotNull(FieldAfterJSON))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportActionAudit) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportActionAudit) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportActionAudit) predicate.SupportActionAudit {
	return predicate.SupportActionAudit(sql.NotPredicates(p))
}
