// Code generated by ent, DO NOT EDIT.

package intention

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Intention {
	return predicate.Intention(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Intention {
	return predicate.Intention(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Intention {
	return predicate.Intention(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Intention {
	return predicate.Intention(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Intention {
	return predicate.Intention(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Intention {
	return predicate.Intention(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Intention {
	return predicate.Intention(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Intention {
	return predicate.Intention(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Intention {
	return predicate.Intention(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldUserID, v))
}

// IntentionText applies equality check predicate on the "intention_text" field. It's identical to IntentionTextEQ.
func IntentionText(v string) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldIntentionText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Intention {
	return predicate.Intention(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Intention {
	return predicate.Intention(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Intention {
	return predicate.Intention(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Intention {
	return predicate.Intention(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Intention {
	return predicate.Intention(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Intention {
	return predicate.Intention(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Intention {
	return predicate.Intention(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Intention {
	return predicate.Intention(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Intention {
	return predicate.Intention(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Intention {
	return predicate.Intention(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Intention {
	return predicate.Intention(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Intention {
	return predicate.Intention(sql.FieldContainsFold(FieldUserID, v))
}

// IntentionTextEQ applies the EQ predicate on the "intention_text" field.
func IntentionTextEQ(v string) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldIntentionText, v))
}

// IntentionTextNEQ applies the NEQ predicate on the "intention_text" field.
func IntentionTextNEQ(v string) predicate.Intention {
	return predicate.Intention(sql.FieldNEQ(FieldIntentionText, v))
}

// IntentionTextIn applies the In predicate on the "intention_text" field.
func IntentionTextIn(vs ...string) predicate.Intention {
	return predicate.Intention(sql.FieldIn(FieldIntentionText, vs...))
}

// IntentionTextNotIn applies the NotIn predicate on the "intention_text" field.
func IntentionTextNotIn(vs ...string) predicate.Intention {
	return predicate.Intention(sql.FieldNotIn(FieldIntentionText, vs...))
}

// IntentionTextGT applies the GT predicate on the "intention_text" field.
func IntentionTextGT(v string) predicate.Intention {
	return predicate.Intention(sql.FieldGT(FieldIntentionText, v))
}

// IntentionTextGTE applies the GTE predicate on the "intention_text" field.
func IntentionTextGTE(v string) predicate.Intention {
	return predicate.Intention(sql.FieldGTE(FieldIntentionText, v))
}

// IntentionTextLT applies the LT predicate on the "intention_text" field.
func IntentionTextLT(v string) predicate.Intention {
	return predicate.Intention(sql.FieldLT(FieldIntentionText, v))
}

// IntentionTextLTE applies the LTE predicate on the "intention_text" field.
func IntentionTextLTE(v string) predicate.Intention {
	return predicate.Intention(sql.FieldLTE(FieldIntentionText, v))
}

// IntentionTextContains applies the Contains predicate on the "intention_text" field.
func IntentionTextContains(v string) predicate.Intention {
	return predicate.Intention(sql.FieldContains(FieldIntentionText, v))
}

// IntentionTextHasPrefix applies the HasPrefix predicate on the "intention_text" field.
func IntentionTextHasPrefix(v string) predicate.Intention {
	return predicate.Intention(sql.FieldHasPrefix(FieldIntentionText, v))
}

// IntentionTextHasSuffix applies the HasSuffix predicate on the "intention_text" field.
func IntentionTextHasSuffix(v string) predicate.Intention {
	return predicate.Intention(sql.FieldHasSuffix(FieldIntentionText, v))
}

// IntentionTextEqualFold applies the EqualFold predicate on the "intention_text" field.
func IntentionTextEqualFold(v string) predicate.Intention {
	return predicate.Intention(sql.FieldEqualFold(FieldIntentionText, v))
}

// IntentionTextContainsFold applies the ContainsFold predicate on the "intention_text" field.
func IntentionTextContainsFold(v string) predicate.Intention {
	return predicate.Intention(sql.FieldContainsFold(FieldIntentionText, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Intention {
	return predicate.Intention(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Intention {
	return predicate.Intention(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Intention {
	return predicate.Intention(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Intention {
	return predicate.Intention(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Intention) predicate.Intention {
	return predicate.Intention(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Intention) predicate.Intention {
	return predicate.Intention(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Intention) predicate.Intention {
	return predicate.Intention(sql.NotPredicates(p))
}
