// Code generated by ent, DO NOT EDIT.

package releasecohort

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the releasecohort type in the database.
	Label = "release_cohort"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRolloutID holds the string denoting the rollout_id field in the database.
	FieldRolloutID = "rollout_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPercentage holds the string denoting the percentage field in the database.
	FieldPercentage = "percentage"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldAppVersionConstraint holds the string denoting the app_version_constraint field in the database.
	FieldAppVersionConstraint = "app_version_constraint"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the releasecohort in the database.
	Table = "release_cohorts"
)

// Columns holds all SQL columns for releasecohort fields.
var Columns = []string{
	FieldID,
	FieldRolloutID,
	FieldPlatform,
	FieldPercentage,
	FieldOrganizationID,
	FieldAppVersionConstraint,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformAndroid Platform = "android"
	PlatformWindows Platform = "windows"
	PlatformLinux   Platform = "linux"
	PlatformMacos   Platform = "macos"
	PlatformWeb     Platform = "web"
	PlatformAll     Platform = "all"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformAndroid, PlatformWindows, PlatformLinux, PlatformMacos, PlatformWeb, PlatformAll:
		return nil
	default:
		return fmt.Errorf("releasecohort: invalid enum value for platform field: %q", pl)
	}
}

// OrderOption defines the ordering options for the ReleaseCohort queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRolloutID orders the results by the rollout_id field.
func ByRolloutID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRolloutID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPercentage orders the results by the percentage field.
func ByPercentage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPercentage, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByAppVersionConstraint orders the results by the app_version_constraint field.
func ByAppVersionConstraint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersionConstraint, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
