// Code generated by ent, DO NOT EDIT.

package approvalrequest

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the approvalrequest type in the database.
	Label = "approval_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldPartnerLinkID holds the string denoting the partner_link_id field in the database.
	FieldPartnerLinkID = "partner_link_id"
	// FieldQuickTokenHash holds the string denoting the quick_token_hash field in the database.
	FieldQuickTokenHash = "quick_token_hash"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldRequestedDurationMinutes holds the string denoting the requested_duration_minutes field in the database.
	FieldRequestedDurationMinutes = "requested_duration_minutes"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldResolvedBy holds the string denoting the resolved_by field in the database.
	FieldResolvedBy = "resolved_by"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the approvalrequest in the database.
	Table = "approval_requests"
)

// Columns holds all SQL columns for approvalrequest fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDeviceID,
	FieldPartnerLinkID,
	FieldQuickTokenHash,
	FieldAction,
	FieldStatus,
	FieldReason,
	FieldRequestedDurationMinutes,
	FieldExpiresAt,
	FieldResolvedBy,
	FieldResolvedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Action defines the type for the "action" enum field.
type Action string

// Action values.
const (
	ActionDisableProtection Action = "disable_protection"
	ActionRemovePartner     Action = "remove_partner"
	ActionUninstallDetected Action = "uninstall_detected"
	ActionResetSettings     Action = "reset_settings"
	ActionPauseProtection   Action = "pause_protection"
	ActionEmergencyAccess   Action = "emergency_access"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionDisableProtection, ActionRemovePartner, ActionUninstallDetected, ActionResetSettings, ActionPauseProtection, ActionEmergencyAccess:
		return nil
	default:
		return fmt.Errorf("approvalrequest: invalid enum value for action field: %q", a)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusApproved  Status = "approved"
	StatusDenied    Status = "denied"
	StatusExpired   Status = "expired"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusApproved, StatusDenied, StatusExpired, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("approvalrequest: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ApprovalRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByPartnerLinkID orders the results by the partner_link_id field.
func ByPartnerLinkID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPartnerLinkID, opts...).ToFunc()
}

// ByQuickTokenHash orders the results by the quick_token_hash field.
func ByQuickTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuickTokenHash, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByRequestedDurationMinutes orders the results by the requested_duration_minutes field.
func ByRequestedDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedDurationMinutes, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByResolvedBy orders the results by the resolved_by field.
func ByResolvedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedBy, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
