// Code generated by ent, DO NOT EDIT.

package educationrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContainsFold(FieldID, id))
}

// ModuleID applies equality check predicate on the "module_id" field. It's identical to ModuleIDEQ.
func ModuleID(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldModuleID, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldRevision, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldSlug, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// ModuleIDEQ applies the EQ predicate on the "module_id" field.
func ModuleIDEQ(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldModuleID, v))
}

// ModuleIDNEQ applies the NEQ predicate on the "module_id" field.
func ModuleIDNEQ(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldModuleID, v))
}

// ModuleIDIn applies the In predicate on the "module_id" field.
func ModuleIDIn(vs ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldModuleID, vs...))
}

// ModuleIDNotIn applies the NotIn predicate on the "module_id" field.
func ModuleIDNotIn(vs ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldModuleID, vs...))
}

// ModuleIDGT applies the GT predicate on the "module_id" field.
func ModuleIDGT(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGT(FieldModuleID, v))
}

// ModuleIDGTE applies the GTE predicate on the "module_id" field.
func ModuleIDGTE(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGTE(FieldModuleID, v))
}

// ModuleIDLT applies the LT predicate on the "module_id" field.
func ModuleIDLT(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLT(FieldModuleID, v))
}

// ModuleIDLTE applies the LTE predicate on the "module_id" field.
func ModuleIDLTE(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLTE(FieldModuleID, v))
}

// ModuleIDContains applies the Contains predicate on the "module_id" field.
func ModuleIDContains(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContains(FieldModuleID, v))
}

// ModuleIDHasPrefix applies the HasPrefix predicate on the "module_id" field.
func ModuleIDHasPrefix(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldHasPrefix(FieldModuleID, v))
}

// ModuleIDHasSuffix applies the HasSuffix predicate on the "module_id" field.
func ModuleIDHasSuffix(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldHasSuffix(FieldModuleID, v))
}

// ModuleIDEqualFold applies the EqualFold predicate on the "module_id" field.
func ModuleIDEqualFold(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEqualFold(FieldModuleID, v))
}

// ModuleIDContainsFold applies the ContainsFold predicate on the "module_id" field.
func ModuleIDContainsFold(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContainsFold(FieldModuleID, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLTE(FieldRevision, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContainsFold(FieldSlug, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldKind, vs...))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EducationRevision {
	return predicate.EducationRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EducationRevision) predicate.EducationRevision {
	return predicate.EducationRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EducationRevision) predicate.EducationRevision {
	return predicate.EducationRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EducationRevision) predicate.EducationRevision {
	return predicate.EducationRevision(sql.NotPredicates(p))
}
