// Code generated by ent, DO NOT EDIT.

package spkpreference

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the spkpreference type in the database.
	Label = "spk_preference"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSpkRecommendationEnabled holds the string denoting the spk_recommendation_enabled field in the database.
	FieldSpkRecommendationEnabled = "spk_recommendation_enabled"
	// FieldSpkUseProtection holds the string denoting the spk_use_protection field in the database.
	FieldSpkUseProtection = "spk_use_protection"
	// FieldSpkUseRecovery holds the string denoting the spk_use_recovery field in the database.
	FieldSpkUseRecovery = "spk_use_recovery"
	// FieldSpkUsePersonal holds the string denoting the spk_use_personal field in the database.
	FieldSpkUsePersonal = "spk_use_personal"
	// FieldLlmPersonalizationEnabled holds the string denoting the llm_personalization_enabled field in the database.
	FieldLlmPersonalizationEnabled = "llm_personalization_enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the spkpreference in the database.
	Table = "spk_preferences"
)

// Columns holds all SQL columns for spkpreference fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSpkRecommendationEnabled,
	FieldSpkUseProtection,
	FieldSpkUseRecovery,
	FieldSpkUsePersonal,
	FieldLlmPersonalizationEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSpkRecommendationEnabled holds the default value on creation for the "spk_recommendation_enabled" field.
	DefaultSpkRecommendationEnabled bool
	// DefaultSpkUseProtection holds the default value on creation for the "spk_use_protection" field.
	DefaultSpkUseProtection bool
	// DefaultSpkUseRecovery holds the default value on creation for the "spk_use_recovery" field.
	DefaultSpkUseRecovery bool
	// DefaultSpkUsePersonal holds the default value on creation for the "spk_use_personal" field.
	DefaultSpkUsePersonal bool
	// DefaultLlmPersonalizationEnabled holds the default value on creation for the "llm_personalization_enabled" field.
	DefaultLlmPersonalizationEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the SpkPreference queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySpkRecommendationEnabled orders the results by the spk_recommendation_enabled field.
func BySpkRecommendationEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpkRecommendationEnabled, opts...).ToFunc()
}

// BySpkUseProtection orders the results by the spk_use_protection field.
func BySpkUseProtection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpkUseProtection, opts...).ToFunc()
}

// BySpkUseRecovery orders the results by the spk_use_recovery field.
func BySpkUseRecovery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpkUseRecovery, opts...).ToFunc()
}

// BySpkUsePersonal orders the results by the spk_use_personal field.
func BySpkUsePersonal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpkUsePersonal, opts...).ToFunc()
}

// ByLlmPersonalizationEnabled orders the results by the llm_personalization_enabled field.
func ByLlmPersonalizationEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLlmPersonalizationEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
