// Code generated by ent, DO NOT EDIT.

package spkpreference

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldUserID, v))
}

// SpkRecommendationEnabled applies equality check predicate on the "spk_recommendation_enabled" field. It's identical to SpkRecommendationEnabledEQ.
func SpkRecommendationEnabled(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkRecommendationEnabled, v))
}

// SpkUseProtection applies equality check predicate on the "spk_use_protection" field. It's identical to SpkUseProtectionEQ.
func SpkUseProtection(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkUseProtection, v))
}

// SpkUseRecovery applies equality check predicate on the "spk_use_recovery" field. It's identical to SpkUseRecoveryEQ.
func SpkUseRecovery(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkUseRecovery, v))
}

// SpkUsePersonal applies equality check predicate on the "spk_use_personal" field. It's identical to SpkUsePersonalEQ.
func SpkUsePersonal(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkUsePersonal, v))
}

// LlmPersonalizationEnabled applies equality check predicate on the "llm_personalization_enabled" field. It's identical to LlmPersonalizationEnabledEQ.
func LlmPersonalizationEnabled(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldLlmPersonalizationEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldContainsFold(FieldUserID, v))
}

// SpkRecommendationEnabledEQ applies the EQ predicate on the "spk_recommendation_enabled" field.
func SpkRecommendationEnabledEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkRecommendationEnabled, v))
}

// SpkRecommendationEnabledNEQ applies the NEQ predicate on the "spk_recommendation_enabled" field.
func SpkRecommendationEnabledNEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldSpkRecommendationEnabled, v))
}

// SpkUseProtectionEQ applies the EQ predicate on the "spk_use_protection" field.
func SpkUseProtectionEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkUseProtection, v))
}

// SpkUseProtectionNEQ applies the NEQ predicate on the "spk_use_protection" field.
func SpkUseProtectionNEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldSpkUseProtection, v))
}

// SpkUseRecoveryEQ applies the EQ predicate on the "spk_use_recovery" field.
func SpkUseRecoveryEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkUseRecovery, v))
}

// SpkUseRecoveryNEQ applies the NEQ predicate on the "spk_use_recovery" field.
func SpkUseRecoveryNEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldSpkUseRecovery, v))
}

// SpkUsePersonalEQ applies the EQ predicate on the "spk_use_personal" field.
func SpkUsePersonalEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldSpkUsePersonal, v))
}

// SpkUsePersonalNEQ applies the NEQ predicate on the "spk_use_personal" field.
func SpkUsePersonalNEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldSpkUsePersonal, v))
}

// LlmPersonalizationEnabledEQ applies the EQ predicate on the "llm_personalization_enabled" field.
func LlmPersonalizationEnabledEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldLlmPersonalizationEnabled, v))
}

// LlmPersonalizationEnabledNEQ applies the NEQ predicate on the "llm_personalization_enabled" field.
func LlmPersonalizationEnabledNEQ(v bool) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldLlmPersonalizationEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SpkPreference {
	return predicate.SpkPreference(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpkPreference) predicate.SpkPreference {
	return predicate.SpkPreference(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpkPreference) predicate.SpkPreference {
	return predicate.SpkPreference(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpkPreference) predicate.SpkPreference {
	return predicate.SpkPreference(sql.NotPredicates(p))
}
