// Code generated by ent, DO NOT EDIT.

package accountabilitymembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldContainsFold(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldGroupID, v))
}

// StudentID applies equality check predicate on the "student_id" field. It's identical to StudentIDEQ.
func StudentID(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldStudentID, v))
}

// ShareProtectionHealth applies equality check predicate on the "share_protection_health" field. It's identical to ShareProtectionHealthEQ.
func ShareProtectionHealth(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareProtectionHealth, v))
}

// ShareProtectionActivity applies equality check predicate on the "share_protection_activity" field. It's identical to ShareProtectionActivityEQ.
func ShareProtectionActivity(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareProtectionActivity, v))
}

// ShareRecoveryEngagement applies equality check predicate on the "share_recovery_engagement" field. It's identical to ShareRecoveryEngagementEQ.
func ShareRecoveryEngagement(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareRecoveryEngagement, v))
}

// ShareEducationProgress applies equality check predicate on the "share_education_progress" field. It's identical to ShareEducationProgressEQ.
func ShareEducationProgress(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareEducationProgress, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldJoinedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldEndedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldContainsFold(FieldGroupID, v))
}

// StudentIDEQ applies the EQ predicate on the "student_id" field.
func StudentIDEQ(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldStudentID, v))
}

// StudentIDNEQ applies the NEQ predicate on the "student_id" field.
func StudentIDNEQ(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldStudentID, v))
}

// StudentIDIn applies the In predicate on the "student_id" field.
func StudentIDIn(vs ...string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldStudentID, vs...))
}

// StudentIDNotIn applies the NotIn predicate on the "student_id" field.
func StudentIDNotIn(vs ...string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldStudentID, vs...))
}

// StudentIDGT applies the GT predicate on the "student_id" field.
func StudentIDGT(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldStudentID, v))
}

// StudentIDGTE applies the GTE predicate on the "student_id" field.
func StudentIDGTE(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldStudentID, v))
}

// StudentIDLT applies the LT predicate on the "student_id" field.
func StudentIDLT(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldStudentID, v))
}

// StudentIDLTE applies the LTE predicate on the "student_id" field.
func StudentIDLTE(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldStudentID, v))
}

// StudentIDContains applies the Contains predicate on the "student_id" field.
func StudentIDContains(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldContains(FieldStudentID, v))
}

// StudentIDHasPrefix applies the HasPrefix predicate on the "student_id" field.
func StudentIDHasPrefix(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldHasPrefix(FieldStudentID, v))
}

// StudentIDHasSuffix applies the HasSuffix predicate on the "student_id" field.
func StudentIDHasSuffix(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldHasSuffix(FieldStudentID, v))
}

// StudentIDEqualFold applies the EqualFold predicate on the "student_id" field.
func StudentIDEqualFold(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEqualFold(FieldStudentID, v))
}

// StudentIDContainsFold applies the ContainsFold predicate on the "student_id" field.
func StudentIDContainsFold(v string) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldContainsFold(FieldStudentID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldStatus, vs...))
}

// ShareProtectionHealthEQ applies the EQ predicate on the "share_protection_health" field.
func ShareProtectionHealthEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareProtectionHealth, v))
}

// ShareProtectionHealthNEQ applies the NEQ predicate on the "share_protection_health" field.
func ShareProtectionHealthNEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldShareProtectionHealth, v))
}

// ShareProtectionActivityEQ applies the EQ predicate on the "share_protection_activity" field.
func ShareProtectionActivityEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareProtectionActivity, v))
}

// ShareProtectionActivityNEQ applies the NEQ predicate on the "share_protection_activity" field.
func ShareProtectionActivityNEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldShareProtectionActivity, v))
}

// ShareRecoveryEngagementEQ applies the EQ predicate on the "share_recovery_engagement" field.
func ShareRecoveryEngagementEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareRecoveryEngagement, v))
}

// ShareRecoveryEngagementNEQ applies the NEQ predicate on the "share_recovery_engagement" field.
func ShareRecoveryEngagementNEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldShareRecoveryEngagement, v))
}

// ShareEducationProgressEQ applies the EQ predicate on the "share_education_progress" field.
func ShareEducationProgressEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldShareEducationProgress, v))
}

// ShareEducationProgressNEQ applies the NEQ predicate on the "share_education_progress" field.
func ShareEducationProgressNEQ(v bool) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldShareEducationProgress, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldJoinedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotNull(FieldEndedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountabilityMembership) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountabilityMembership) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountabilityMembership) predicate.AccountabilityMembership {
	return predicate.AccountabilityMembership(sql.NotPredicates(p))
}
