// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/aggregateevent"
)

// AggregateEventCreate is the builder for creating a AggregateEvent entity.
type AggregateEventCreate struct {
	config
	mutation *AggregateEventMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AggregateEventCreate) SetUserID(v string) *AggregateEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *AggregateEventCreate) SetDeviceID(v string) *AggregateEventCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *AggregateEventCreate) SetNillableDeviceID(v *string) *AggregateEventCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *AggregateEventCreate) SetIdempotencyKey(v string) *AggregateEventCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *AggregateEventCreate) SetNillableIdempotencyKey(v *string) *AggregateEventCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *AggregateEventCreate) SetEventType(v aggregateevent.EventType) *AggregateEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetEventDate sets the "event_date" field.
func (_c *AggregateEventCreate) SetEventDate(v time.Time) *AggregateEventCreate {
	_c.mutation.SetEventDate(v)
	return _c
}

// SetCount sets the "count" field.
func (_c *AggregateEventCreate) SetCount(v int) *AggregateEventCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetMetadataJSON sets the "metadata_json" field.
func (_c *AggregateEventCreate) SetMetadataJSON(v map[string]interface{}) *AggregateEventCreate {
	_c.mutation.SetMetadataJSON(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AggregateEventCreate) SetCreatedAt(v time.Time) *AggregateEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AggregateEventCreate) SetNillableCreatedAt(v *time.Time) *AggregateEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AggregateEventCreate) SetID(v string) *AggregateEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AggregateEventCreate) SetNillableID(v *string) *AggregateEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AggregateEventMutation object of the builder.
func (_c *AggregateEventCreate) Mutation() *AggregateEventMutation {
	return _c.mutation
}

// Save creates the AggregateEvent in the database.
func (_c *AggregateEventCreate) Save(ctx context.Context) (*AggregateEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AggregateEventCreate) SaveX(ctx context.Context) *AggregateEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AggregateEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AggregateEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AggregateEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := aggregateevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aggregateevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AggregateEventCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AggregateEvent.user_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "AggregateEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := aggregateevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AggregateEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventDate(); !ok {
		return &ValidationError{Name: "event_date", err: errors.New(`ent: missing required field "AggregateEvent.event_date"`)}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "AggregateEvent.count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AggregateEvent.created_at"`)}
	}
	return nil
}

func (_c *AggregateEventCreate) sqlSave(ctx context.Context) (*AggregateEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AggregateEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AggregateEventCreate) createSpec() (*AggregateEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AggregateEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aggregateevent.Table, sqlgraph.NewFieldSpec(aggregateevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(aggregateevent.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(aggregateevent.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(aggregateevent.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(aggregateevent.FieldEventType, field.TypeEnum, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.EventDate(); ok {
		_spec.SetField(aggregateevent.FieldEventDate, field.TypeTime, value)
		_node.EventDate = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(aggregateevent.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.MetadataJSON(); ok {
		_spec.SetField(aggregateevent.FieldMetadataJSON, field.TypeJSON, value)
		_node.MetadataJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aggregateevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AggregateEventCreateBulk is the builder for creating many AggregateEvent entities in bulk.
type AggregateEventCreateBulk struct {
	config
	err      error
	builders []*AggregateEventCreate
}

// Save creates the AggregateEvent entities in the database.
func (_c *AggregateEventCreateBulk) Save(ctx context.Context) ([]*AggregateEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AggregateEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AggregateEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AggregateEventCreateBulk) SaveX(ctx context.Context) []*AggregateEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AggregateEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AggregateEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
