// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/aggregateevent"
)

// AggregateEvent is the model entity for the AggregateEvent schema.
type AggregateEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID *string `json:"device_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType aggregateevent.EventType `json:"event_type,omitempty"`
	// EventDate holds the value of the "event_date" field.
	EventDate time.Time `json:"event_date,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// MetadataJSON holds the value of the "metadata_json" field.
	MetadataJSON map[string]interface{} `json:"metadata_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AggregateEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aggregateevent.FieldMetadataJSON:
			values[i] = new([]byte)
		case aggregateevent.FieldCount:
			values[i] = new(sql.NullInt64)
		case aggregateevent.FieldID, aggregateevent.FieldUserID, aggregateevent.FieldDeviceID, aggregateevent.FieldEventType:
			values[i] = new(sql.NullString)
		case aggregateevent.FieldEventDate, aggregateevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AggregateEvent fields.
func (_m *AggregateEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aggregateevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case aggregateevent.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case aggregateevent.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = new(string)
				*_m.DeviceID = value.String
			}
		case aggregateevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = aggregateevent.EventType(value.String)
			}
		case aggregateevent.FieldEventDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_date", values[i])
			} else if value.Valid {
				_m.EventDate = value.Time
			}
		case aggregateevent.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case aggregateevent.FieldMetadataJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MetadataJSON); err != nil {
					return fmt.Errorf("unmarshal field metadata_json: %w", err)
				}
			}
		case aggregateevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AggregateEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AggregateEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AggregateEvent.
// Note that you need to call AggregateEvent.Unwrap() before calling this method if this AggregateEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AggregateEvent) Update() *AggregateEventUpdateOne {
	return NewAggregateEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AggregateEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AggregateEvent) Unwrap() *AggregateEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AggregateEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AggregateEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AggregateEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	if v := _m.DeviceID; v != nil {
		builder.WriteString("device_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventType))
	builder.WriteString(", ")
	builder.WriteString("event_date=")
	builder.WriteString(_m.EventDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("metadata_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataJSON))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AggregateEvents is a parsable slice of AggregateEvent.
type AggregateEvents []*AggregateEvent
