// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/blockedevent"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// BlockedEventUpdate is the builder for updating BlockedEvent entities.
type BlockedEventUpdate struct {
	config
	hooks    []Hook
	mutation *BlockedEventMutation
}

// Where appends a list predicates to the BlockedEventUpdate builder.
func (_u *BlockedEventUpdate) Where(ps ...predicate.BlockedEvent) *BlockedEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BlockedEventUpdate) SetUserID(v string) *BlockedEventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BlockedEventUpdate) SetNillableUserID(v *string) *BlockedEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *BlockedEventUpdate) SetDeviceID(v string) *BlockedEventUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *BlockedEventUpdate) SetNillableDeviceID(v *string) *BlockedEventUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// ClearDeviceID clears the value of the "device_id" field.
func (_u *BlockedEventUpdate) ClearDeviceID() *BlockedEventUpdate {
	_u.mutation.ClearDeviceID()
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *BlockedEventUpdate) SetOccurredAt(v time.Time) *BlockedEventUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *BlockedEventUpdate) SetNillableOccurredAt(v *time.Time) *BlockedEventUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// Mutation returns the BlockedEventMutation object of the builder.
func (_u *BlockedEventUpdate) Mutation() *BlockedEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlockedEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlockedEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlockedEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlockedEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BlockedEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(blockedevent.Table, blockedevent.Columns, sqlgraph.NewFieldSpec(blockedevent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(blockedevent.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(blockedevent.FieldDeviceID, field.TypeString, value)
	}
	if _u.mutation.DeviceIDCleared() {
		_spec.ClearField(blockedevent.FieldDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(blockedevent.FieldOccurredAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blockedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlockedEventUpdateOne is the builder for updating a single BlockedEvent entity.
type BlockedEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlockedEventMutation
}

// SetUserID sets the "user_id" field.
func (_u *BlockedEventUpdateOne) SetUserID(v string) *BlockedEventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BlockedEventUpdateOne) SetNillableUserID(v *string) *BlockedEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *BlockedEventUpdateOne) SetDeviceID(v string) *BlockedEventUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *BlockedEventUpdateOne) SetNillableDeviceID(v *string) *BlockedEventUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// ClearDeviceID clears the value of the "device_id" field.
func (_u *BlockedEventUpdateOne) ClearDeviceID() *BlockedEventUpdateOne {
	_u.mutation.ClearDeviceID()
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *BlockedEventUpdateOne) SetOccurredAt(v time.Time) *BlockedEventUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *BlockedEventUpdateOne) SetNillableOccurredAt(v *time.Time) *BlockedEventUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// Mutation returns the BlockedEventMutation object of the builder.
func (_u *BlockedEventUpdateOne) Mutation() *BlockedEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the BlockedEventUpdate builder.
func (_u *BlockedEventUpdateOne) Where(ps ...predicate.BlockedEvent) *BlockedEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlockedEventUpdateOne) Select(field string, fields ...string) *BlockedEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BlockedEvent entity.
func (_u *BlockedEventUpdateOne) Save(ctx context.Context) (*BlockedEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlockedEventUpdateOne) SaveX(ctx context.Context) *BlockedEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlockedEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlockedEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BlockedEventUpdateOne) sqlSave(ctx context.Context) (_node *BlockedEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(blockedevent.Table, blockedevent.Columns, sqlgraph.NewFieldSpec(blockedevent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BlockedEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blockedevent.FieldID)
		for _, f := range fields {
			if !blockedevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blockedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(blockedevent.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(blockedevent.FieldDeviceID, field.TypeString, value)
	}
	if _u.mutation.DeviceIDCleared() {
		_spec.ClearField(blockedevent.FieldDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(blockedevent.FieldOccurredAt, field.TypeTime, value)
	}
	_node = &BlockedEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blockedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
