// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/blockedevent"
)

// BlockedEventCreate is the builder for creating a BlockedEvent entity.
type BlockedEventCreate struct {
	config
	mutation *BlockedEventMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *BlockedEventCreate) SetUserID(v string) *BlockedEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *BlockedEventCreate) SetDeviceID(v string) *BlockedEventCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *BlockedEventCreate) SetNillableDeviceID(v *string) *BlockedEventCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *BlockedEventCreate) SetOccurredAt(v time.Time) *BlockedEventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlockedEventCreate) SetCreatedAt(v time.Time) *BlockedEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlockedEventCreate) SetNillableCreatedAt(v *time.Time) *BlockedEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BlockedEventCreate) SetID(v string) *BlockedEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BlockedEventCreate) SetNillableID(v *string) *BlockedEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the BlockedEventMutation object of the builder.
func (_c *BlockedEventCreate) Mutation() *BlockedEventMutation {
	return _c.mutation
}

// Save creates the BlockedEvent in the database.
func (_c *BlockedEventCreate) Save(ctx context.Context) (*BlockedEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlockedEventCreate) SaveX(ctx context.Context) *BlockedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlockedEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlockedEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlockedEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blockedevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := blockedevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlockedEventCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BlockedEvent.user_id"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "BlockedEvent.occurred_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BlockedEvent.created_at"`)}
	}
	return nil
}

func (_c *BlockedEventCreate) sqlSave(ctx context.Context) (*BlockedEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BlockedEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlockedEventCreate) createSpec() (*BlockedEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &BlockedEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blockedevent.Table, sqlgraph.NewFieldSpec(blockedevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(blockedevent.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(blockedevent.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = &value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(blockedevent.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blockedevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// BlockedEventCreateBulk is the builder for creating many BlockedEvent entities in bulk.
type BlockedEventCreateBulk struct {
	config
	err      error
	builders []*BlockedEventCreate
}

// Save creates the BlockedEvent entities in the database.
func (_c *BlockedEventCreateBulk) Save(ctx context.Context) ([]*BlockedEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BlockedEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlockedEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlockedEventCreateBulk) SaveX(ctx context.Context) []*BlockedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlockedEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlockedEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
