// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/contactverification"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ContactVerificationUpdate is the builder for updating ContactVerification entities.
type ContactVerificationUpdate struct {
	config
	hooks    []Hook
	mutation *ContactVerificationMutation
}

// Where appends a list predicates to the ContactVerificationUpdate builder.
func (_u *ContactVerificationUpdate) Where(ps ...predicate.ContactVerification) *ContactVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ContactVerificationUpdate) SetUserID(v string) *ContactVerificationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableUserID(v *string) *ContactVerificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ContactVerificationUpdate) SetKind(v contactverification.Kind) *ContactVerificationUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableKind(v *contactverification.Kind) *ContactVerificationUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *ContactVerificationUpdate) SetDestination(v string) *ContactVerificationUpdate {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableDestination(v *string) *ContactVerificationUpdate {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ContactVerificationUpdate) SetTokenHash(v string) *ContactVerificationUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableTokenHash(v *string) *ContactVerificationUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *ContactVerificationUpdate) SetAttemptCount(v int) *ContactVerificationUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableAttemptCount(v *int) *ContactVerificationUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *ContactVerificationUpdate) AddAttemptCount(v int) *ContactVerificationUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ContactVerificationUpdate) SetExpiresAt(v time.Time) *ContactVerificationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableExpiresAt(v *time.Time) *ContactVerificationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *ContactVerificationUpdate) SetConsumedAt(v time.Time) *ContactVerificationUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *ContactVerificationUpdate) SetNillableConsumedAt(v *time.Time) *ContactVerificationUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *ContactVerificationUpdate) ClearConsumedAt() *ContactVerificationUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the ContactVerificationMutation object of the builder.
func (_u *ContactVerificationUpdate) Mutation() *ContactVerificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContactVerificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContactVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContactVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContactVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContactVerificationUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := contactverification.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ContactVerification.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ContactVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contactverification.Table, contactverification.Columns, sqlgraph.NewFieldSpec(contactverification.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(contactverification.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(contactverification.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(contactverification.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(contactverification.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(contactverification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(contactverification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(contactverification.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(contactverification.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(contactverification.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contactverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContactVerificationUpdateOne is the builder for updating a single ContactVerification entity.
type ContactVerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContactVerificationMutation
}

// SetUserID sets the "user_id" field.
func (_u *ContactVerificationUpdateOne) SetUserID(v string) *ContactVerificationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableUserID(v *string) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ContactVerificationUpdateOne) SetKind(v contactverification.Kind) *ContactVerificationUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableKind(v *contactverification.Kind) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *ContactVerificationUpdateOne) SetDestination(v string) *ContactVerificationUpdateOne {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableDestination(v *string) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ContactVerificationUpdateOne) SetTokenHash(v string) *ContactVerificationUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableTokenHash(v *string) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *ContactVerificationUpdateOne) SetAttemptCount(v int) *ContactVerificationUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableAttemptCount(v *int) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *ContactVerificationUpdateOne) AddAttemptCount(v int) *ContactVerificationUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ContactVerificationUpdateOne) SetExpiresAt(v time.Time) *ContactVerificationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableExpiresAt(v *time.Time) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *ContactVerificationUpdateOne) SetConsumedAt(v time.Time) *ContactVerificationUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *ContactVerificationUpdateOne) SetNillableConsumedAt(v *time.Time) *ContactVerificationUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *ContactVerificationUpdateOne) ClearConsumedAt() *ContactVerificationUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the ContactVerificationMutation object of the builder.
func (_u *ContactVerificationUpdateOne) Mutation() *ContactVerificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContactVerificationUpdate builder.
func (_u *ContactVerificationUpdateOne) Where(ps ...predicate.ContactVerification) *ContactVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContactVerificationUpdateOne) Select(field string, fields ...string) *ContactVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContactVerification entity.
func (_u *ContactVerificationUpdateOne) Save(ctx context.Context) (*ContactVerification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContactVerificationUpdateOne) SaveX(ctx context.Context) *ContactVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContactVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContactVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContactVerificationUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := contactverification.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ContactVerification.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ContactVerificationUpdateOne) sqlSave(ctx context.Context) (_node *ContactVerification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contactverification.Table, contactverification.Columns, sqlgraph.NewFieldSpec(contactverification.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContactVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contactverification.FieldID)
		for _, f := range fields {
			if !contactverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contactverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(contactverification.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(contactverification.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(contactverification.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(contactverification.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(contactverification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(contactverification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(contactverification.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(contactverification.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(contactverification.FieldConsumedAt, field.TypeTime)
	}
	_node = &ContactVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contactverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
