// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/downloadapp"
	"github.com/gamblock-ai/gamblock-ai-backend/internal/model"
)

// DownloadAppCreate is the builder for creating a DownloadApp entity.
type DownloadAppCreate struct {
	config
	mutation *DownloadAppMutation
	hooks    []Hook
}

// SetPlatform sets the "platform" field.
func (_c *DownloadAppCreate) SetPlatform(v downloadapp.Platform) *DownloadAppCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetEyebrowJSON sets the "eyebrow_json" field.
func (_c *DownloadAppCreate) SetEyebrowJSON(v model.LocalizedText) *DownloadAppCreate {
	_c.mutation.SetEyebrowJSON(v)
	return _c
}

// SetTitleJSON sets the "title_json" field.
func (_c *DownloadAppCreate) SetTitleJSON(v model.LocalizedText) *DownloadAppCreate {
	_c.mutation.SetTitleJSON(v)
	return _c
}

// SetDescriptionJSON sets the "description_json" field.
func (_c *DownloadAppCreate) SetDescriptionJSON(v model.LocalizedText) *DownloadAppCreate {
	_c.mutation.SetDescriptionJSON(v)
	return _c
}

// SetRequirementsJSON sets the "requirements_json" field.
func (_c *DownloadAppCreate) SetRequirementsJSON(v model.LocalizedText) *DownloadAppCreate {
	_c.mutation.SetRequirementsJSON(v)
	return _c
}

// SetArchitectureJSON sets the "architecture_json" field.
func (_c *DownloadAppCreate) SetArchitectureJSON(v model.LocalizedText) *DownloadAppCreate {
	_c.mutation.SetArchitectureJSON(v)
	return _c
}

// SetFeaturesJSON sets the "features_json" field.
func (_c *DownloadAppCreate) SetFeaturesJSON(v []model.LocalizedText) *DownloadAppCreate {
	_c.mutation.SetFeaturesJSON(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *DownloadAppCreate) SetVersion(v string) *DownloadAppCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetAssetsJSON sets the "assets_json" field.
func (_c *DownloadAppCreate) SetAssetsJSON(v []model.DownloadAsset) *DownloadAppCreate {
	_c.mutation.SetAssetsJSON(v)
	return _c
}

// SetPublished sets the "published" field.
func (_c *DownloadAppCreate) SetPublished(v bool) *DownloadAppCreate {
	_c.mutation.SetPublished(v)
	return _c
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_c *DownloadAppCreate) SetNillablePublished(v *bool) *DownloadAppCreate {
	if v != nil {
		_c.SetPublished(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DownloadAppCreate) SetUpdatedBy(v string) *DownloadAppCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DownloadAppCreate) SetCreatedAt(v time.Time) *DownloadAppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DownloadAppCreate) SetNillableCreatedAt(v *time.Time) *DownloadAppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DownloadAppCreate) SetUpdatedAt(v time.Time) *DownloadAppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DownloadAppCreate) SetNillableUpdatedAt(v *time.Time) *DownloadAppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DownloadAppCreate) SetID(v string) *DownloadAppCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DownloadAppCreate) SetNillableID(v *string) *DownloadAppCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DownloadAppMutation object of the builder.
func (_c *DownloadAppCreate) Mutation() *DownloadAppMutation {
	return _c.mutation
}

// Save creates the DownloadApp in the database.
func (_c *DownloadAppCreate) Save(ctx context.Context) (*DownloadApp, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DownloadAppCreate) SaveX(ctx context.Context) *DownloadApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownloadAppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownloadAppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DownloadAppCreate) defaults() {
	if _, ok := _c.mutation.Published(); !ok {
		v := downloadapp.DefaultPublished
		_c.mutation.SetPublished(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := downloadapp.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := downloadapp.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := downloadapp.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DownloadAppCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "DownloadApp.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := downloadapp.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "DownloadApp.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EyebrowJSON(); !ok {
		return &ValidationError{Name: "eyebrow_json", err: errors.New(`ent: missing required field "DownloadApp.eyebrow_json"`)}
	}
	if _, ok := _c.mutation.TitleJSON(); !ok {
		return &ValidationError{Name: "title_json", err: errors.New(`ent: missing required field "DownloadApp.title_json"`)}
	}
	if _, ok := _c.mutation.DescriptionJSON(); !ok {
		return &ValidationError{Name: "description_json", err: errors.New(`ent: missing required field "DownloadApp.description_json"`)}
	}
	if _, ok := _c.mutation.RequirementsJSON(); !ok {
		return &ValidationError{Name: "requirements_json", err: errors.New(`ent: missing required field "DownloadApp.requirements_json"`)}
	}
	if _, ok := _c.mutation.ArchitectureJSON(); !ok {
		return &ValidationError{Name: "architecture_json", err: errors.New(`ent: missing required field "DownloadApp.architecture_json"`)}
	}
	if _, ok := _c.mutation.FeaturesJSON(); !ok {
		return &ValidationError{Name: "features_json", err: errors.New(`ent: missing required field "DownloadApp.features_json"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DownloadApp.version"`)}
	}
	if _, ok := _c.mutation.AssetsJSON(); !ok {
		return &ValidationError{Name: "assets_json", err: errors.New(`ent: missing required field "DownloadApp.assets_json"`)}
	}
	if _, ok := _c.mutation.Published(); !ok {
		return &ValidationError{Name: "published", err: errors.New(`ent: missing required field "DownloadApp.published"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "DownloadApp.updated_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DownloadApp.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DownloadApp.updated_at"`)}
	}
	return nil
}

func (_c *DownloadAppCreate) sqlSave(ctx context.Context) (*DownloadApp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DownloadApp.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DownloadAppCreate) createSpec() (*DownloadApp, *sqlgraph.CreateSpec) {
	var (
		_node = &DownloadApp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(downloadapp.Table, sqlgraph.NewFieldSpec(downloadapp.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(downloadapp.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.EyebrowJSON(); ok {
		_spec.SetField(downloadapp.FieldEyebrowJSON, field.TypeJSON, value)
		_node.EyebrowJSON = value
	}
	if value, ok := _c.mutation.TitleJSON(); ok {
		_spec.SetField(downloadapp.FieldTitleJSON, field.TypeJSON, value)
		_node.TitleJSON = value
	}
	if value, ok := _c.mutation.DescriptionJSON(); ok {
		_spec.SetField(downloadapp.FieldDescriptionJSON, field.TypeJSON, value)
		_node.DescriptionJSON = value
	}
	if value, ok := _c.mutation.RequirementsJSON(); ok {
		_spec.SetField(downloadapp.FieldRequirementsJSON, field.TypeJSON, value)
		_node.RequirementsJSON = value
	}
	if value, ok := _c.mutation.ArchitectureJSON(); ok {
		_spec.SetField(downloadapp.FieldArchitectureJSON, field.TypeJSON, value)
		_node.ArchitectureJSON = value
	}
	if value, ok := _c.mutation.FeaturesJSON(); ok {
		_spec.SetField(downloadapp.FieldFeaturesJSON, field.TypeJSON, value)
		_node.FeaturesJSON = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(downloadapp.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.AssetsJSON(); ok {
		_spec.SetField(downloadapp.FieldAssetsJSON, field.TypeJSON, value)
		_node.AssetsJSON = value
	}
	if value, ok := _c.mutation.Published(); ok {
		_spec.SetField(downloadapp.FieldPublished, field.TypeBool, value)
		_node.Published = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(downloadapp.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(downloadapp.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(downloadapp.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DownloadAppCreateBulk is the builder for creating many DownloadApp entities in bulk.
type DownloadAppCreateBulk struct {
	config
	err      error
	builders []*DownloadAppCreate
}

// Save creates the DownloadApp entities in the database.
func (_c *DownloadAppCreateBulk) Save(ctx context.Context) ([]*DownloadApp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DownloadApp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DownloadAppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DownloadAppCreateBulk) SaveX(ctx context.Context) []*DownloadApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownloadAppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownloadAppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
