// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/emergencykeyrequest"
)

// EmergencyKeyRequestCreate is the builder for creating a EmergencyKeyRequest entity.
type EmergencyKeyRequestCreate struct {
	config
	mutation *EmergencyKeyRequestMutation
	hooks    []Hook
}

// SetRequestedBy sets the "requested_by" field.
func (_c *EmergencyKeyRequestCreate) SetRequestedBy(v string) *EmergencyKeyRequestCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetApprovedBy sets the "approved_by" field.
func (_c *EmergencyKeyRequestCreate) SetApprovedBy(v string) *EmergencyKeyRequestCreate {
	_c.mutation.SetApprovedBy(v)
	return _c
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableApprovedBy(v *string) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetApprovedBy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EmergencyKeyRequestCreate) SetStatus(v emergencykeyrequest.Status) *EmergencyKeyRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableStatus(v *emergencykeyrequest.Status) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *EmergencyKeyRequestCreate) SetKeyHash(v string) *EmergencyKeyRequestCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableKeyHash(v *string) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetKeyHash(*v)
	}
	return _c
}

// SetRequestExpiresAt sets the "request_expires_at" field.
func (_c *EmergencyKeyRequestCreate) SetRequestExpiresAt(v time.Time) *EmergencyKeyRequestCreate {
	_c.mutation.SetRequestExpiresAt(v)
	return _c
}

// SetKeyExpiresAt sets the "key_expires_at" field.
func (_c *EmergencyKeyRequestCreate) SetKeyExpiresAt(v time.Time) *EmergencyKeyRequestCreate {
	_c.mutation.SetKeyExpiresAt(v)
	return _c
}

// SetNillableKeyExpiresAt sets the "key_expires_at" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableKeyExpiresAt(v *time.Time) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetKeyExpiresAt(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *EmergencyKeyRequestCreate) SetApprovedAt(v time.Time) *EmergencyKeyRequestCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableApprovedAt(v *time.Time) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmergencyKeyRequestCreate) SetCreatedAt(v time.Time) *EmergencyKeyRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableCreatedAt(v *time.Time) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmergencyKeyRequestCreate) SetUpdatedAt(v time.Time) *EmergencyKeyRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableUpdatedAt(v *time.Time) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmergencyKeyRequestCreate) SetID(v string) *EmergencyKeyRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EmergencyKeyRequestCreate) SetNillableID(v *string) *EmergencyKeyRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the EmergencyKeyRequestMutation object of the builder.
func (_c *EmergencyKeyRequestCreate) Mutation() *EmergencyKeyRequestMutation {
	return _c.mutation
}

// Save creates the EmergencyKeyRequest in the database.
func (_c *EmergencyKeyRequestCreate) Save(ctx context.Context) (*EmergencyKeyRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmergencyKeyRequestCreate) SaveX(ctx context.Context) *EmergencyKeyRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmergencyKeyRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmergencyKeyRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmergencyKeyRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := emergencykeyrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emergencykeyrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emergencykeyrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := emergencykeyrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmergencyKeyRequestCreate) check() error {
	if _, ok := _c.mutation.RequestedBy(); !ok {
		return &ValidationError{Name: "requested_by", err: errors.New(`ent: missing required field "EmergencyKeyRequest.requested_by"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EmergencyKeyRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := emergencykeyrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmergencyKeyRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestExpiresAt(); !ok {
		return &ValidationError{Name: "request_expires_at", err: errors.New(`ent: missing required field "EmergencyKeyRequest.request_expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmergencyKeyRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmergencyKeyRequest.updated_at"`)}
	}
	return nil
}

func (_c *EmergencyKeyRequestCreate) sqlSave(ctx context.Context) (*EmergencyKeyRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EmergencyKeyRequest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmergencyKeyRequestCreate) createSpec() (*EmergencyKeyRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &EmergencyKeyRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emergencykeyrequest.Table, sqlgraph.NewFieldSpec(emergencykeyrequest.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequestedBy(); ok {
		_spec.SetField(emergencykeyrequest.FieldRequestedBy, field.TypeString, value)
		_node.RequestedBy = value
	}
	if value, ok := _c.mutation.ApprovedBy(); ok {
		_spec.SetField(emergencykeyrequest.FieldApprovedBy, field.TypeString, value)
		_node.ApprovedBy = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(emergencykeyrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(emergencykeyrequest.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = &value
	}
	if value, ok := _c.mutation.RequestExpiresAt(); ok {
		_spec.SetField(emergencykeyrequest.FieldRequestExpiresAt, field.TypeTime, value)
		_node.RequestExpiresAt = value
	}
	if value, ok := _c.mutation.KeyExpiresAt(); ok {
		_spec.SetField(emergencykeyrequest.FieldKeyExpiresAt, field.TypeTime, value)
		_node.KeyExpiresAt = &value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(emergencykeyrequest.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emergencykeyrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emergencykeyrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EmergencyKeyRequestCreateBulk is the builder for creating many EmergencyKeyRequest entities in bulk.
type EmergencyKeyRequestCreateBulk struct {
	config
	err      error
	builders []*EmergencyKeyRequestCreate
}

// Save creates the EmergencyKeyRequest entities in the database.
func (_c *EmergencyKeyRequestCreateBulk) Save(ctx context.Context) ([]*EmergencyKeyRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmergencyKeyRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmergencyKeyRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmergencyKeyRequestCreateBulk) SaveX(ctx context.Context) []*EmergencyKeyRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmergencyKeyRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmergencyKeyRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
