// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/intention"
)

// Intention is the model entity for the Intention schema.
type Intention struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// IntentionText holds the value of the "intention_text" field.
	IntentionText string `json:"intention_text,omitempty"`
	// Status holds the value of the "status" field.
	Status intention.Status `json:"status,omitempty"`
	// Pernah ga gara-gara judol jadi ninggalin sekolah/kuliah
	SchoolImpact *intention.SchoolImpact `json:"school_impact,omitempty"`
	// Seberapa besar uang yang udah dihabisin buat judol
	MoneySpent *intention.MoneySpent `json:"money_spent,omitempty"`
	// Berapa lama screen time judol per hari
	ScreenTime *intention.ScreenTime `json:"screen_time,omitempty"`
	// Pernah nyoba berhenti judol sebelumnya
	QuitAttempts *intention.QuitAttempts `json:"quit_attempts,omitempty"`
	// Seberapa yakin mau berhenti total dari judol
	QuitMotivation *intention.QuitMotivation `json:"quit_motivation,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Intention) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intention.FieldID, intention.FieldUserID, intention.FieldIntentionText, intention.FieldStatus, intention.FieldSchoolImpact, intention.FieldMoneySpent, intention.FieldScreenTime, intention.FieldQuitAttempts, intention.FieldQuitMotivation:
			values[i] = new(sql.NullString)
		case intention.FieldCreatedAt, intention.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Intention fields.
func (_m *Intention) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intention.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case intention.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case intention.FieldIntentionText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field intention_text", values[i])
			} else if value.Valid {
				_m.IntentionText = value.String
			}
		case intention.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = intention.Status(value.String)
			}
		case intention.FieldSchoolImpact:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field school_impact", values[i])
			} else if value.Valid {
				_m.SchoolImpact = new(intention.SchoolImpact)
				*_m.SchoolImpact = intention.SchoolImpact(value.String)
			}
		case intention.FieldMoneySpent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field money_spent", values[i])
			} else if value.Valid {
				_m.MoneySpent = new(intention.MoneySpent)
				*_m.MoneySpent = intention.MoneySpent(value.String)
			}
		case intention.FieldScreenTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field screen_time", values[i])
			} else if value.Valid {
				_m.ScreenTime = new(intention.ScreenTime)
				*_m.ScreenTime = intention.ScreenTime(value.String)
			}
		case intention.FieldQuitAttempts:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quit_attempts", values[i])
			} else if value.Valid {
				_m.QuitAttempts = new(intention.QuitAttempts)
				*_m.QuitAttempts = intention.QuitAttempts(value.String)
			}
		case intention.FieldQuitMotivation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quit_motivation", values[i])
			} else if value.Valid {
				_m.QuitMotivation = new(intention.QuitMotivation)
				*_m.QuitMotivation = intention.QuitMotivation(value.String)
			}
		case intention.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case intention.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Intention.
// This includes values selected through modifiers, order, etc.
func (_m *Intention) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Intention.
// Note that you need to call Intention.Unwrap() before calling this method if this Intention
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Intention) Update() *IntentionUpdateOne {
	return NewIntentionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Intention entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Intention) Unwrap() *Intention {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Intention is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Intention) String() string {
	var builder strings.Builder
	builder.WriteString("Intention(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("intention_text=")
	builder.WriteString(_m.IntentionText)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.SchoolImpact; v != nil {
		builder.WriteString("school_impact=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MoneySpent; v != nil {
		builder.WriteString("money_spent=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ScreenTime; v != nil {
		builder.WriteString("screen_time=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.QuitAttempts; v != nil {
		builder.WriteString("quit_attempts=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.QuitMotivation; v != nil {
		builder.WriteString("quit_motivation=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Intentions is a parsable slice of Intention.
type Intentions []*Intention
