// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/interventionrecord"
)

// InterventionRecordCreate is the builder for creating a InterventionRecord entity.
type InterventionRecordCreate struct {
	config
	mutation *InterventionRecordMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *InterventionRecordCreate) SetUserID(v string) *InterventionRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInterventionKey sets the "intervention_key" field.
func (_c *InterventionRecordCreate) SetInterventionKey(v string) *InterventionRecordCreate {
	_c.mutation.SetInterventionKey(v)
	return _c
}

// SetResponseType sets the "response_type" field.
func (_c *InterventionRecordCreate) SetResponseType(v string) *InterventionRecordCreate {
	_c.mutation.SetResponseType(v)
	return _c
}

// SetSupportLevel sets the "support_level" field.
func (_c *InterventionRecordCreate) SetSupportLevel(v interventionrecord.SupportLevel) *InterventionRecordCreate {
	_c.mutation.SetSupportLevel(v)
	return _c
}

// SetEngagementLevel sets the "engagement_level" field.
func (_c *InterventionRecordCreate) SetEngagementLevel(v interventionrecord.EngagementLevel) *InterventionRecordCreate {
	_c.mutation.SetEngagementLevel(v)
	return _c
}

// SetReadinessLevel sets the "readiness_level" field.
func (_c *InterventionRecordCreate) SetReadinessLevel(v string) *InterventionRecordCreate {
	_c.mutation.SetReadinessLevel(v)
	return _c
}

// SetNillableReadinessLevel sets the "readiness_level" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableReadinessLevel(v *string) *InterventionRecordCreate {
	if v != nil {
		_c.SetReadinessLevel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InterventionRecordCreate) SetStatus(v interventionrecord.Status) *InterventionRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableStatus(v *interventionrecord.Status) *InterventionRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRecommendedAt sets the "recommended_at" field.
func (_c *InterventionRecordCreate) SetRecommendedAt(v time.Time) *InterventionRecordCreate {
	_c.mutation.SetRecommendedAt(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *InterventionRecordCreate) SetCompletedAt(v time.Time) *InterventionRecordCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableCompletedAt(v *time.Time) *InterventionRecordCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetEffectivenessStatus sets the "effectiveness_status" field.
func (_c *InterventionRecordCreate) SetEffectivenessStatus(v interventionrecord.EffectivenessStatus) *InterventionRecordCreate {
	_c.mutation.SetEffectivenessStatus(v)
	return _c
}

// SetNillableEffectivenessStatus sets the "effectiveness_status" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableEffectivenessStatus(v *interventionrecord.EffectivenessStatus) *InterventionRecordCreate {
	if v != nil {
		_c.SetEffectivenessStatus(*v)
	}
	return _c
}

// SetPersonalizedMessage sets the "personalized_message" field.
func (_c *InterventionRecordCreate) SetPersonalizedMessage(v string) *InterventionRecordCreate {
	_c.mutation.SetPersonalizedMessage(v)
	return _c
}

// SetNillablePersonalizedMessage sets the "personalized_message" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillablePersonalizedMessage(v *string) *InterventionRecordCreate {
	if v != nil {
		_c.SetPersonalizedMessage(*v)
	}
	return _c
}

// SetPersonalizedExplanation sets the "personalized_explanation" field.
func (_c *InterventionRecordCreate) SetPersonalizedExplanation(v string) *InterventionRecordCreate {
	_c.mutation.SetPersonalizedExplanation(v)
	return _c
}

// SetNillablePersonalizedExplanation sets the "personalized_explanation" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillablePersonalizedExplanation(v *string) *InterventionRecordCreate {
	if v != nil {
		_c.SetPersonalizedExplanation(*v)
	}
	return _c
}

// SetLlmUsed sets the "llm_used" field.
func (_c *InterventionRecordCreate) SetLlmUsed(v bool) *InterventionRecordCreate {
	_c.mutation.SetLlmUsed(v)
	return _c
}

// SetNillableLlmUsed sets the "llm_used" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableLlmUsed(v *bool) *InterventionRecordCreate {
	if v != nil {
		_c.SetLlmUsed(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InterventionRecordCreate) SetCreatedAt(v time.Time) *InterventionRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableCreatedAt(v *time.Time) *InterventionRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InterventionRecordCreate) SetUpdatedAt(v time.Time) *InterventionRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableUpdatedAt(v *time.Time) *InterventionRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InterventionRecordCreate) SetID(v string) *InterventionRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InterventionRecordCreate) SetNillableID(v *string) *InterventionRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InterventionRecordMutation object of the builder.
func (_c *InterventionRecordCreate) Mutation() *InterventionRecordMutation {
	return _c.mutation
}

// Save creates the InterventionRecord in the database.
func (_c *InterventionRecordCreate) Save(ctx context.Context) (*InterventionRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InterventionRecordCreate) SaveX(ctx context.Context) *InterventionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InterventionRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InterventionRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InterventionRecordCreate) defaults() {
	if _, ok := _c.mutation.ReadinessLevel(); !ok {
		v := interventionrecord.DefaultReadinessLevel
		_c.mutation.SetReadinessLevel(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := interventionrecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.EffectivenessStatus(); !ok {
		v := interventionrecord.DefaultEffectivenessStatus
		_c.mutation.SetEffectivenessStatus(v)
	}
	if _, ok := _c.mutation.LlmUsed(); !ok {
		v := interventionrecord.DefaultLlmUsed
		_c.mutation.SetLlmUsed(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := interventionrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := interventionrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := interventionrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InterventionRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InterventionRecord.user_id"`)}
	}
	if _, ok := _c.mutation.InterventionKey(); !ok {
		return &ValidationError{Name: "intervention_key", err: errors.New(`ent: missing required field "InterventionRecord.intervention_key"`)}
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		return &ValidationError{Name: "response_type", err: errors.New(`ent: missing required field "InterventionRecord.response_type"`)}
	}
	if _, ok := _c.mutation.SupportLevel(); !ok {
		return &ValidationError{Name: "support_level", err: errors.New(`ent: missing required field "InterventionRecord.support_level"`)}
	}
	if v, ok := _c.mutation.SupportLevel(); ok {
		if err := interventionrecord.SupportLevelValidator(v); err != nil {
			return &ValidationError{Name: "support_level", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.support_level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EngagementLevel(); !ok {
		return &ValidationError{Name: "engagement_level", err: errors.New(`ent: missing required field "InterventionRecord.engagement_level"`)}
	}
	if v, ok := _c.mutation.EngagementLevel(); ok {
		if err := interventionrecord.EngagementLevelValidator(v); err != nil {
			return &ValidationError{Name: "engagement_level", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.engagement_level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InterventionRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := interventionrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecommendedAt(); !ok {
		return &ValidationError{Name: "recommended_at", err: errors.New(`ent: missing required field "InterventionRecord.recommended_at"`)}
	}
	if _, ok := _c.mutation.EffectivenessStatus(); !ok {
		return &ValidationError{Name: "effectiveness_status", err: errors.New(`ent: missing required field "InterventionRecord.effectiveness_status"`)}
	}
	if v, ok := _c.mutation.EffectivenessStatus(); ok {
		if err := interventionrecord.EffectivenessStatusValidator(v); err != nil {
			return &ValidationError{Name: "effectiveness_status", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.effectiveness_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LlmUsed(); !ok {
		return &ValidationError{Name: "llm_used", err: errors.New(`ent: missing required field "InterventionRecord.llm_used"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InterventionRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InterventionRecord.updated_at"`)}
	}
	return nil
}

func (_c *InterventionRecordCreate) sqlSave(ctx context.Context) (*InterventionRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected InterventionRecord.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InterventionRecordCreate) createSpec() (*InterventionRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &InterventionRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(interventionrecord.Table, sqlgraph.NewFieldSpec(interventionrecord.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(interventionrecord.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.InterventionKey(); ok {
		_spec.SetField(interventionrecord.FieldInterventionKey, field.TypeString, value)
		_node.InterventionKey = value
	}
	if value, ok := _c.mutation.ResponseType(); ok {
		_spec.SetField(interventionrecord.FieldResponseType, field.TypeString, value)
		_node.ResponseType = value
	}
	if value, ok := _c.mutation.SupportLevel(); ok {
		_spec.SetField(interventionrecord.FieldSupportLevel, field.TypeEnum, value)
		_node.SupportLevel = value
	}
	if value, ok := _c.mutation.EngagementLevel(); ok {
		_spec.SetField(interventionrecord.FieldEngagementLevel, field.TypeEnum, value)
		_node.EngagementLevel = value
	}
	if value, ok := _c.mutation.ReadinessLevel(); ok {
		_spec.SetField(interventionrecord.FieldReadinessLevel, field.TypeString, value)
		_node.ReadinessLevel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(interventionrecord.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RecommendedAt(); ok {
		_spec.SetField(interventionrecord.FieldRecommendedAt, field.TypeTime, value)
		_node.RecommendedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(interventionrecord.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.EffectivenessStatus(); ok {
		_spec.SetField(interventionrecord.FieldEffectivenessStatus, field.TypeEnum, value)
		_node.EffectivenessStatus = value
	}
	if value, ok := _c.mutation.PersonalizedMessage(); ok {
		_spec.SetField(interventionrecord.FieldPersonalizedMessage, field.TypeString, value)
		_node.PersonalizedMessage = &value
	}
	if value, ok := _c.mutation.PersonalizedExplanation(); ok {
		_spec.SetField(interventionrecord.FieldPersonalizedExplanation, field.TypeString, value)
		_node.PersonalizedExplanation = &value
	}
	if value, ok := _c.mutation.LlmUsed(); ok {
		_spec.SetField(interventionrecord.FieldLlmUsed, field.TypeBool, value)
		_node.LlmUsed = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(interventionrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(interventionrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// InterventionRecordCreateBulk is the builder for creating many InterventionRecord entities in bulk.
type InterventionRecordCreateBulk struct {
	config
	err      error
	builders []*InterventionRecordCreate
}

// Save creates the InterventionRecord entities in the database.
func (_c *InterventionRecordCreateBulk) Save(ctx context.Context) ([]*InterventionRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InterventionRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InterventionRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InterventionRecordCreateBulk) SaveX(ctx context.Context) []*InterventionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InterventionRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InterventionRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
