// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/interventionrecord"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// InterventionRecordUpdate is the builder for updating InterventionRecord entities.
type InterventionRecordUpdate struct {
	config
	hooks    []Hook
	mutation *InterventionRecordMutation
}

// Where appends a list predicates to the InterventionRecordUpdate builder.
func (_u *InterventionRecordUpdate) Where(ps ...predicate.InterventionRecord) *InterventionRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InterventionRecordUpdate) SetUserID(v string) *InterventionRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableUserID(v *string) *InterventionRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInterventionKey sets the "intervention_key" field.
func (_u *InterventionRecordUpdate) SetInterventionKey(v string) *InterventionRecordUpdate {
	_u.mutation.SetInterventionKey(v)
	return _u
}

// SetNillableInterventionKey sets the "intervention_key" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableInterventionKey(v *string) *InterventionRecordUpdate {
	if v != nil {
		_u.SetInterventionKey(*v)
	}
	return _u
}

// SetResponseType sets the "response_type" field.
func (_u *InterventionRecordUpdate) SetResponseType(v string) *InterventionRecordUpdate {
	_u.mutation.SetResponseType(v)
	return _u
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableResponseType(v *string) *InterventionRecordUpdate {
	if v != nil {
		_u.SetResponseType(*v)
	}
	return _u
}

// SetSupportLevel sets the "support_level" field.
func (_u *InterventionRecordUpdate) SetSupportLevel(v interventionrecord.SupportLevel) *InterventionRecordUpdate {
	_u.mutation.SetSupportLevel(v)
	return _u
}

// SetNillableSupportLevel sets the "support_level" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableSupportLevel(v *interventionrecord.SupportLevel) *InterventionRecordUpdate {
	if v != nil {
		_u.SetSupportLevel(*v)
	}
	return _u
}

// SetEngagementLevel sets the "engagement_level" field.
func (_u *InterventionRecordUpdate) SetEngagementLevel(v interventionrecord.EngagementLevel) *InterventionRecordUpdate {
	_u.mutation.SetEngagementLevel(v)
	return _u
}

// SetNillableEngagementLevel sets the "engagement_level" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableEngagementLevel(v *interventionrecord.EngagementLevel) *InterventionRecordUpdate {
	if v != nil {
		_u.SetEngagementLevel(*v)
	}
	return _u
}

// SetReadinessLevel sets the "readiness_level" field.
func (_u *InterventionRecordUpdate) SetReadinessLevel(v string) *InterventionRecordUpdate {
	_u.mutation.SetReadinessLevel(v)
	return _u
}

// SetNillableReadinessLevel sets the "readiness_level" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableReadinessLevel(v *string) *InterventionRecordUpdate {
	if v != nil {
		_u.SetReadinessLevel(*v)
	}
	return _u
}

// ClearReadinessLevel clears the value of the "readiness_level" field.
func (_u *InterventionRecordUpdate) ClearReadinessLevel() *InterventionRecordUpdate {
	_u.mutation.ClearReadinessLevel()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InterventionRecordUpdate) SetStatus(v interventionrecord.Status) *InterventionRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableStatus(v *interventionrecord.Status) *InterventionRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecommendedAt sets the "recommended_at" field.
func (_u *InterventionRecordUpdate) SetRecommendedAt(v time.Time) *InterventionRecordUpdate {
	_u.mutation.SetRecommendedAt(v)
	return _u
}

// SetNillableRecommendedAt sets the "recommended_at" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableRecommendedAt(v *time.Time) *InterventionRecordUpdate {
	if v != nil {
		_u.SetRecommendedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *InterventionRecordUpdate) SetCompletedAt(v time.Time) *InterventionRecordUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableCompletedAt(v *time.Time) *InterventionRecordUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *InterventionRecordUpdate) ClearCompletedAt() *InterventionRecordUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetEffectivenessStatus sets the "effectiveness_status" field.
func (_u *InterventionRecordUpdate) SetEffectivenessStatus(v interventionrecord.EffectivenessStatus) *InterventionRecordUpdate {
	_u.mutation.SetEffectivenessStatus(v)
	return _u
}

// SetNillableEffectivenessStatus sets the "effectiveness_status" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableEffectivenessStatus(v *interventionrecord.EffectivenessStatus) *InterventionRecordUpdate {
	if v != nil {
		_u.SetEffectivenessStatus(*v)
	}
	return _u
}

// SetPersonalizedMessage sets the "personalized_message" field.
func (_u *InterventionRecordUpdate) SetPersonalizedMessage(v string) *InterventionRecordUpdate {
	_u.mutation.SetPersonalizedMessage(v)
	return _u
}

// SetNillablePersonalizedMessage sets the "personalized_message" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillablePersonalizedMessage(v *string) *InterventionRecordUpdate {
	if v != nil {
		_u.SetPersonalizedMessage(*v)
	}
	return _u
}

// ClearPersonalizedMessage clears the value of the "personalized_message" field.
func (_u *InterventionRecordUpdate) ClearPersonalizedMessage() *InterventionRecordUpdate {
	_u.mutation.ClearPersonalizedMessage()
	return _u
}

// SetPersonalizedExplanation sets the "personalized_explanation" field.
func (_u *InterventionRecordUpdate) SetPersonalizedExplanation(v string) *InterventionRecordUpdate {
	_u.mutation.SetPersonalizedExplanation(v)
	return _u
}

// SetNillablePersonalizedExplanation sets the "personalized_explanation" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillablePersonalizedExplanation(v *string) *InterventionRecordUpdate {
	if v != nil {
		_u.SetPersonalizedExplanation(*v)
	}
	return _u
}

// ClearPersonalizedExplanation clears the value of the "personalized_explanation" field.
func (_u *InterventionRecordUpdate) ClearPersonalizedExplanation() *InterventionRecordUpdate {
	_u.mutation.ClearPersonalizedExplanation()
	return _u
}

// SetLlmUsed sets the "llm_used" field.
func (_u *InterventionRecordUpdate) SetLlmUsed(v bool) *InterventionRecordUpdate {
	_u.mutation.SetLlmUsed(v)
	return _u
}

// SetNillableLlmUsed sets the "llm_used" field if the given value is not nil.
func (_u *InterventionRecordUpdate) SetNillableLlmUsed(v *bool) *InterventionRecordUpdate {
	if v != nil {
		_u.SetLlmUsed(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InterventionRecordUpdate) SetUpdatedAt(v time.Time) *InterventionRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InterventionRecordMutation object of the builder.
func (_u *InterventionRecordUpdate) Mutation() *InterventionRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InterventionRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InterventionRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InterventionRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InterventionRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InterventionRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := interventionrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InterventionRecordUpdate) check() error {
	if v, ok := _u.mutation.SupportLevel(); ok {
		if err := interventionrecord.SupportLevelValidator(v); err != nil {
			return &ValidationError{Name: "support_level", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.support_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EngagementLevel(); ok {
		if err := interventionrecord.EngagementLevelValidator(v); err != nil {
			return &ValidationError{Name: "engagement_level", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.engagement_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := interventionrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EffectivenessStatus(); ok {
		if err := interventionrecord.EffectivenessStatusValidator(v); err != nil {
			return &ValidationError{Name: "effectiveness_status", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.effectiveness_status": %w`, err)}
		}
	}
	return nil
}

func (_u *InterventionRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(interventionrecord.Table, interventionrecord.Columns, sqlgraph.NewFieldSpec(interventionrecord.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(interventionrecord.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InterventionKey(); ok {
		_spec.SetField(interventionrecord.FieldInterventionKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseType(); ok {
		_spec.SetField(interventionrecord.FieldResponseType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupportLevel(); ok {
		_spec.SetField(interventionrecord.FieldSupportLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EngagementLevel(); ok {
		_spec.SetField(interventionrecord.FieldEngagementLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReadinessLevel(); ok {
		_spec.SetField(interventionrecord.FieldReadinessLevel, field.TypeString, value)
	}
	if _u.mutation.ReadinessLevelCleared() {
		_spec.ClearField(interventionrecord.FieldReadinessLevel, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(interventionrecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RecommendedAt(); ok {
		_spec.SetField(interventionrecord.FieldRecommendedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(interventionrecord.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(interventionrecord.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EffectivenessStatus(); ok {
		_spec.SetField(interventionrecord.FieldEffectivenessStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PersonalizedMessage(); ok {
		_spec.SetField(interventionrecord.FieldPersonalizedMessage, field.TypeString, value)
	}
	if _u.mutation.PersonalizedMessageCleared() {
		_spec.ClearField(interventionrecord.FieldPersonalizedMessage, field.TypeString)
	}
	if value, ok := _u.mutation.PersonalizedExplanation(); ok {
		_spec.SetField(interventionrecord.FieldPersonalizedExplanation, field.TypeString, value)
	}
	if _u.mutation.PersonalizedExplanationCleared() {
		_spec.ClearField(interventionrecord.FieldPersonalizedExplanation, field.TypeString)
	}
	if value, ok := _u.mutation.LlmUsed(); ok {
		_spec.SetField(interventionrecord.FieldLlmUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(interventionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interventionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InterventionRecordUpdateOne is the builder for updating a single InterventionRecord entity.
type InterventionRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InterventionRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *InterventionRecordUpdateOne) SetUserID(v string) *InterventionRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableUserID(v *string) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInterventionKey sets the "intervention_key" field.
func (_u *InterventionRecordUpdateOne) SetInterventionKey(v string) *InterventionRecordUpdateOne {
	_u.mutation.SetInterventionKey(v)
	return _u
}

// SetNillableInterventionKey sets the "intervention_key" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableInterventionKey(v *string) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetInterventionKey(*v)
	}
	return _u
}

// SetResponseType sets the "response_type" field.
func (_u *InterventionRecordUpdateOne) SetResponseType(v string) *InterventionRecordUpdateOne {
	_u.mutation.SetResponseType(v)
	return _u
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableResponseType(v *string) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetResponseType(*v)
	}
	return _u
}

// SetSupportLevel sets the "support_level" field.
func (_u *InterventionRecordUpdateOne) SetSupportLevel(v interventionrecord.SupportLevel) *InterventionRecordUpdateOne {
	_u.mutation.SetSupportLevel(v)
	return _u
}

// SetNillableSupportLevel sets the "support_level" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableSupportLevel(v *interventionrecord.SupportLevel) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetSupportLevel(*v)
	}
	return _u
}

// SetEngagementLevel sets the "engagement_level" field.
func (_u *InterventionRecordUpdateOne) SetEngagementLevel(v interventionrecord.EngagementLevel) *InterventionRecordUpdateOne {
	_u.mutation.SetEngagementLevel(v)
	return _u
}

// SetNillableEngagementLevel sets the "engagement_level" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableEngagementLevel(v *interventionrecord.EngagementLevel) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetEngagementLevel(*v)
	}
	return _u
}

// SetReadinessLevel sets the "readiness_level" field.
func (_u *InterventionRecordUpdateOne) SetReadinessLevel(v string) *InterventionRecordUpdateOne {
	_u.mutation.SetReadinessLevel(v)
	return _u
}

// SetNillableReadinessLevel sets the "readiness_level" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableReadinessLevel(v *string) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetReadinessLevel(*v)
	}
	return _u
}

// ClearReadinessLevel clears the value of the "readiness_level" field.
func (_u *InterventionRecordUpdateOne) ClearReadinessLevel() *InterventionRecordUpdateOne {
	_u.mutation.ClearReadinessLevel()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InterventionRecordUpdateOne) SetStatus(v interventionrecord.Status) *InterventionRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableStatus(v *interventionrecord.Status) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecommendedAt sets the "recommended_at" field.
func (_u *InterventionRecordUpdateOne) SetRecommendedAt(v time.Time) *InterventionRecordUpdateOne {
	_u.mutation.SetRecommendedAt(v)
	return _u
}

// SetNillableRecommendedAt sets the "recommended_at" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableRecommendedAt(v *time.Time) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetRecommendedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *InterventionRecordUpdateOne) SetCompletedAt(v time.Time) *InterventionRecordUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableCompletedAt(v *time.Time) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *InterventionRecordUpdateOne) ClearCompletedAt() *InterventionRecordUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetEffectivenessStatus sets the "effectiveness_status" field.
func (_u *InterventionRecordUpdateOne) SetEffectivenessStatus(v interventionrecord.EffectivenessStatus) *InterventionRecordUpdateOne {
	_u.mutation.SetEffectivenessStatus(v)
	return _u
}

// SetNillableEffectivenessStatus sets the "effectiveness_status" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableEffectivenessStatus(v *interventionrecord.EffectivenessStatus) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetEffectivenessStatus(*v)
	}
	return _u
}

// SetPersonalizedMessage sets the "personalized_message" field.
func (_u *InterventionRecordUpdateOne) SetPersonalizedMessage(v string) *InterventionRecordUpdateOne {
	_u.mutation.SetPersonalizedMessage(v)
	return _u
}

// SetNillablePersonalizedMessage sets the "personalized_message" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillablePersonalizedMessage(v *string) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetPersonalizedMessage(*v)
	}
	return _u
}

// ClearPersonalizedMessage clears the value of the "personalized_message" field.
func (_u *InterventionRecordUpdateOne) ClearPersonalizedMessage() *InterventionRecordUpdateOne {
	_u.mutation.ClearPersonalizedMessage()
	return _u
}

// SetPersonalizedExplanation sets the "personalized_explanation" field.
func (_u *InterventionRecordUpdateOne) SetPersonalizedExplanation(v string) *InterventionRecordUpdateOne {
	_u.mutation.SetPersonalizedExplanation(v)
	return _u
}

// SetNillablePersonalizedExplanation sets the "personalized_explanation" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillablePersonalizedExplanation(v *string) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetPersonalizedExplanation(*v)
	}
	return _u
}

// ClearPersonalizedExplanation clears the value of the "personalized_explanation" field.
func (_u *InterventionRecordUpdateOne) ClearPersonalizedExplanation() *InterventionRecordUpdateOne {
	_u.mutation.ClearPersonalizedExplanation()
	return _u
}

// SetLlmUsed sets the "llm_used" field.
func (_u *InterventionRecordUpdateOne) SetLlmUsed(v bool) *InterventionRecordUpdateOne {
	_u.mutation.SetLlmUsed(v)
	return _u
}

// SetNillableLlmUsed sets the "llm_used" field if the given value is not nil.
func (_u *InterventionRecordUpdateOne) SetNillableLlmUsed(v *bool) *InterventionRecordUpdateOne {
	if v != nil {
		_u.SetLlmUsed(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InterventionRecordUpdateOne) SetUpdatedAt(v time.Time) *InterventionRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InterventionRecordMutation object of the builder.
func (_u *InterventionRecordUpdateOne) Mutation() *InterventionRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the InterventionRecordUpdate builder.
func (_u *InterventionRecordUpdateOne) Where(ps ...predicate.InterventionRecord) *InterventionRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InterventionRecordUpdateOne) Select(field string, fields ...string) *InterventionRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InterventionRecord entity.
func (_u *InterventionRecordUpdateOne) Save(ctx context.Context) (*InterventionRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InterventionRecordUpdateOne) SaveX(ctx context.Context) *InterventionRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InterventionRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InterventionRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InterventionRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := interventionrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InterventionRecordUpdateOne) check() error {
	if v, ok := _u.mutation.SupportLevel(); ok {
		if err := interventionrecord.SupportLevelValidator(v); err != nil {
			return &ValidationError{Name: "support_level", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.support_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EngagementLevel(); ok {
		if err := interventionrecord.EngagementLevelValidator(v); err != nil {
			return &ValidationError{Name: "engagement_level", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.engagement_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := interventionrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EffectivenessStatus(); ok {
		if err := interventionrecord.EffectivenessStatusValidator(v); err != nil {
			return &ValidationError{Name: "effectiveness_status", err: fmt.Errorf(`ent: validator failed for field "InterventionRecord.effectiveness_status": %w`, err)}
		}
	}
	return nil
}

func (_u *InterventionRecordUpdateOne) sqlSave(ctx context.Context) (_node *InterventionRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(interventionrecord.Table, interventionrecord.Columns, sqlgraph.NewFieldSpec(interventionrecord.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InterventionRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interventionrecord.FieldID)
		for _, f := range fields {
			if !interventionrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != interventionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(interventionrecord.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InterventionKey(); ok {
		_spec.SetField(interventionrecord.FieldInterventionKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseType(); ok {
		_spec.SetField(interventionrecord.FieldResponseType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupportLevel(); ok {
		_spec.SetField(interventionrecord.FieldSupportLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EngagementLevel(); ok {
		_spec.SetField(interventionrecord.FieldEngagementLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReadinessLevel(); ok {
		_spec.SetField(interventionrecord.FieldReadinessLevel, field.TypeString, value)
	}
	if _u.mutation.ReadinessLevelCleared() {
		_spec.ClearField(interventionrecord.FieldReadinessLevel, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(interventionrecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RecommendedAt(); ok {
		_spec.SetField(interventionrecord.FieldRecommendedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(interventionrecord.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(interventionrecord.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EffectivenessStatus(); ok {
		_spec.SetField(interventionrecord.FieldEffectivenessStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PersonalizedMessage(); ok {
		_spec.SetField(interventionrecord.FieldPersonalizedMessage, field.TypeString, value)
	}
	if _u.mutation.PersonalizedMessageCleared() {
		_spec.ClearField(interventionrecord.FieldPersonalizedMessage, field.TypeString)
	}
	if value, ok := _u.mutation.PersonalizedExplanation(); ok {
		_spec.SetField(interventionrecord.FieldPersonalizedExplanation, field.TypeString, value)
	}
	if _u.mutation.PersonalizedExplanationCleared() {
		_spec.ClearField(interventionrecord.FieldPersonalizedExplanation, field.TypeString)
	}
	if value, ok := _u.mutation.LlmUsed(); ok {
		_spec.SetField(interventionrecord.FieldLlmUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(interventionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InterventionRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interventionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
