// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/learningcluster"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// LearningClusterUpdate is the builder for updating LearningCluster entities.
type LearningClusterUpdate struct {
	config
	hooks    []Hook
	mutation *LearningClusterMutation
}

// Where appends a list predicates to the LearningClusterUpdate builder.
func (_u *LearningClusterUpdate) Where(ps ...predicate.LearningCluster) *LearningClusterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *LearningClusterUpdate) SetSlug(v string) *LearningClusterUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableSlug(v *string) *LearningClusterUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitleID sets the "title_id" field.
func (_u *LearningClusterUpdate) SetTitleID(v string) *LearningClusterUpdate {
	_u.mutation.SetTitleID(v)
	return _u
}

// SetNillableTitleID sets the "title_id" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableTitleID(v *string) *LearningClusterUpdate {
	if v != nil {
		_u.SetTitleID(*v)
	}
	return _u
}

// SetTitleEn sets the "title_en" field.
func (_u *LearningClusterUpdate) SetTitleEn(v string) *LearningClusterUpdate {
	_u.mutation.SetTitleEn(v)
	return _u
}

// SetNillableTitleEn sets the "title_en" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableTitleEn(v *string) *LearningClusterUpdate {
	if v != nil {
		_u.SetTitleEn(*v)
	}
	return _u
}

// SetDescriptionID sets the "description_id" field.
func (_u *LearningClusterUpdate) SetDescriptionID(v string) *LearningClusterUpdate {
	_u.mutation.SetDescriptionID(v)
	return _u
}

// SetNillableDescriptionID sets the "description_id" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableDescriptionID(v *string) *LearningClusterUpdate {
	if v != nil {
		_u.SetDescriptionID(*v)
	}
	return _u
}

// SetDescriptionEn sets the "description_en" field.
func (_u *LearningClusterUpdate) SetDescriptionEn(v string) *LearningClusterUpdate {
	_u.mutation.SetDescriptionEn(v)
	return _u
}

// SetNillableDescriptionEn sets the "description_en" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableDescriptionEn(v *string) *LearningClusterUpdate {
	if v != nil {
		_u.SetDescriptionEn(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LearningClusterUpdate) SetSortOrder(v int) *LearningClusterUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableSortOrder(v *int) *LearningClusterUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LearningClusterUpdate) AddSortOrder(v int) *LearningClusterUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *LearningClusterUpdate) SetActive(v bool) *LearningClusterUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LearningClusterUpdate) SetNillableActive(v *bool) *LearningClusterUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LearningClusterUpdate) SetUpdatedAt(v time.Time) *LearningClusterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LearningClusterMutation object of the builder.
func (_u *LearningClusterUpdate) Mutation() *LearningClusterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LearningClusterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LearningClusterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LearningClusterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LearningClusterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LearningClusterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := learningcluster.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LearningClusterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(learningcluster.Table, learningcluster.Columns, sqlgraph.NewFieldSpec(learningcluster.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(learningcluster.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleID(); ok {
		_spec.SetField(learningcluster.FieldTitleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleEn(); ok {
		_spec.SetField(learningcluster.FieldTitleEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionID(); ok {
		_spec.SetField(learningcluster.FieldDescriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionEn(); ok {
		_spec.SetField(learningcluster.FieldDescriptionEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(learningcluster.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(learningcluster.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(learningcluster.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(learningcluster.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{learningcluster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LearningClusterUpdateOne is the builder for updating a single LearningCluster entity.
type LearningClusterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LearningClusterMutation
}

// SetSlug sets the "slug" field.
func (_u *LearningClusterUpdateOne) SetSlug(v string) *LearningClusterUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableSlug(v *string) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitleID sets the "title_id" field.
func (_u *LearningClusterUpdateOne) SetTitleID(v string) *LearningClusterUpdateOne {
	_u.mutation.SetTitleID(v)
	return _u
}

// SetNillableTitleID sets the "title_id" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableTitleID(v *string) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetTitleID(*v)
	}
	return _u
}

// SetTitleEn sets the "title_en" field.
func (_u *LearningClusterUpdateOne) SetTitleEn(v string) *LearningClusterUpdateOne {
	_u.mutation.SetTitleEn(v)
	return _u
}

// SetNillableTitleEn sets the "title_en" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableTitleEn(v *string) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetTitleEn(*v)
	}
	return _u
}

// SetDescriptionID sets the "description_id" field.
func (_u *LearningClusterUpdateOne) SetDescriptionID(v string) *LearningClusterUpdateOne {
	_u.mutation.SetDescriptionID(v)
	return _u
}

// SetNillableDescriptionID sets the "description_id" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableDescriptionID(v *string) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetDescriptionID(*v)
	}
	return _u
}

// SetDescriptionEn sets the "description_en" field.
func (_u *LearningClusterUpdateOne) SetDescriptionEn(v string) *LearningClusterUpdateOne {
	_u.mutation.SetDescriptionEn(v)
	return _u
}

// SetNillableDescriptionEn sets the "description_en" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableDescriptionEn(v *string) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetDescriptionEn(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LearningClusterUpdateOne) SetSortOrder(v int) *LearningClusterUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableSortOrder(v *int) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LearningClusterUpdateOne) AddSortOrder(v int) *LearningClusterUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *LearningClusterUpdateOne) SetActive(v bool) *LearningClusterUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LearningClusterUpdateOne) SetNillableActive(v *bool) *LearningClusterUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LearningClusterUpdateOne) SetUpdatedAt(v time.Time) *LearningClusterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LearningClusterMutation object of the builder.
func (_u *LearningClusterUpdateOne) Mutation() *LearningClusterMutation {
	return _u.mutation
}

// Where appends a list predicates to the LearningClusterUpdate builder.
func (_u *LearningClusterUpdateOne) Where(ps ...predicate.LearningCluster) *LearningClusterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LearningClusterUpdateOne) Select(field string, fields ...string) *LearningClusterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LearningCluster entity.
func (_u *LearningClusterUpdateOne) Save(ctx context.Context) (*LearningCluster, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LearningClusterUpdateOne) SaveX(ctx context.Context) *LearningCluster {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LearningClusterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LearningClusterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LearningClusterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := learningcluster.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LearningClusterUpdateOne) sqlSave(ctx context.Context) (_node *LearningCluster, err error) {
	_spec := sqlgraph.NewUpdateSpec(learningcluster.Table, learningcluster.Columns, sqlgraph.NewFieldSpec(learningcluster.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LearningCluster.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, learningcluster.FieldID)
		for _, f := range fields {
			if !learningcluster.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != learningcluster.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(learningcluster.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleID(); ok {
		_spec.SetField(learningcluster.FieldTitleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleEn(); ok {
		_spec.SetField(learningcluster.FieldTitleEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionID(); ok {
		_spec.SetField(learningcluster.FieldDescriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionEn(); ok {
		_spec.SetField(learningcluster.FieldDescriptionEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(learningcluster.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(learningcluster.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(learningcluster.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(learningcluster.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &LearningCluster{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{learningcluster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
