// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/learningitem"
)

// LearningItemCreate is the builder for creating a LearningItem entity.
type LearningItemCreate struct {
	config
	mutation *LearningItemMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *LearningItemCreate) SetSlug(v string) *LearningItemCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *LearningItemCreate) SetKind(v learningitem.Kind) *LearningItemCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTitleID sets the "title_id" field.
func (_c *LearningItemCreate) SetTitleID(v string) *LearningItemCreate {
	_c.mutation.SetTitleID(v)
	return _c
}

// SetTitleEn sets the "title_en" field.
func (_c *LearningItemCreate) SetTitleEn(v string) *LearningItemCreate {
	_c.mutation.SetTitleEn(v)
	return _c
}

// SetSummaryID sets the "summary_id" field.
func (_c *LearningItemCreate) SetSummaryID(v string) *LearningItemCreate {
	_c.mutation.SetSummaryID(v)
	return _c
}

// SetNillableSummaryID sets the "summary_id" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableSummaryID(v *string) *LearningItemCreate {
	if v != nil {
		_c.SetSummaryID(*v)
	}
	return _c
}

// SetSummaryEn sets the "summary_en" field.
func (_c *LearningItemCreate) SetSummaryEn(v string) *LearningItemCreate {
	_c.mutation.SetSummaryEn(v)
	return _c
}

// SetNillableSummaryEn sets the "summary_en" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableSummaryEn(v *string) *LearningItemCreate {
	if v != nil {
		_c.SetSummaryEn(*v)
	}
	return _c
}

// SetDocumentJSON sets the "document_json" field.
func (_c *LearningItemCreate) SetDocumentJSON(v map[string]interface{}) *LearningItemCreate {
	_c.mutation.SetDocumentJSON(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LearningItemCreate) SetStatus(v learningitem.Status) *LearningItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableStatus(v *learningitem.Status) *LearningItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDraftRevision sets the "draft_revision" field.
func (_c *LearningItemCreate) SetDraftRevision(v int) *LearningItemCreate {
	_c.mutation.SetDraftRevision(v)
	return _c
}

// SetNillableDraftRevision sets the "draft_revision" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableDraftRevision(v *int) *LearningItemCreate {
	if v != nil {
		_c.SetDraftRevision(*v)
	}
	return _c
}

// SetPublishedRevision sets the "published_revision" field.
func (_c *LearningItemCreate) SetPublishedRevision(v int) *LearningItemCreate {
	_c.mutation.SetPublishedRevision(v)
	return _c
}

// SetNillablePublishedRevision sets the "published_revision" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillablePublishedRevision(v *int) *LearningItemCreate {
	if v != nil {
		_c.SetPublishedRevision(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *LearningItemCreate) SetPublishedAt(v time.Time) *LearningItemCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillablePublishedAt(v *time.Time) *LearningItemCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetArchivedAt sets the "archived_at" field.
func (_c *LearningItemCreate) SetArchivedAt(v time.Time) *LearningItemCreate {
	_c.mutation.SetArchivedAt(v)
	return _c
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableArchivedAt(v *time.Time) *LearningItemCreate {
	if v != nil {
		_c.SetArchivedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *LearningItemCreate) SetCreatedBy(v string) *LearningItemCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableCreatedBy(v *string) *LearningItemCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *LearningItemCreate) SetUpdatedBy(v string) *LearningItemCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableUpdatedBy(v *string) *LearningItemCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LearningItemCreate) SetCreatedAt(v time.Time) *LearningItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableCreatedAt(v *time.Time) *LearningItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LearningItemCreate) SetUpdatedAt(v time.Time) *LearningItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableUpdatedAt(v *time.Time) *LearningItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LearningItemCreate) SetID(v string) *LearningItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LearningItemCreate) SetNillableID(v *string) *LearningItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LearningItemMutation object of the builder.
func (_c *LearningItemCreate) Mutation() *LearningItemMutation {
	return _c.mutation
}

// Save creates the LearningItem in the database.
func (_c *LearningItemCreate) Save(ctx context.Context) (*LearningItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LearningItemCreate) SaveX(ctx context.Context) *LearningItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LearningItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LearningItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LearningItemCreate) defaults() {
	if _, ok := _c.mutation.SummaryID(); !ok {
		v := learningitem.DefaultSummaryID
		_c.mutation.SetSummaryID(v)
	}
	if _, ok := _c.mutation.SummaryEn(); !ok {
		v := learningitem.DefaultSummaryEn
		_c.mutation.SetSummaryEn(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := learningitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DraftRevision(); !ok {
		v := learningitem.DefaultDraftRevision
		_c.mutation.SetDraftRevision(v)
	}
	if _, ok := _c.mutation.PublishedRevision(); !ok {
		v := learningitem.DefaultPublishedRevision
		_c.mutation.SetPublishedRevision(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := learningitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := learningitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := learningitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LearningItemCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "LearningItem.slug"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "LearningItem.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := learningitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "LearningItem.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TitleID(); !ok {
		return &ValidationError{Name: "title_id", err: errors.New(`ent: missing required field "LearningItem.title_id"`)}
	}
	if _, ok := _c.mutation.TitleEn(); !ok {
		return &ValidationError{Name: "title_en", err: errors.New(`ent: missing required field "LearningItem.title_en"`)}
	}
	if _, ok := _c.mutation.SummaryID(); !ok {
		return &ValidationError{Name: "summary_id", err: errors.New(`ent: missing required field "LearningItem.summary_id"`)}
	}
	if _, ok := _c.mutation.SummaryEn(); !ok {
		return &ValidationError{Name: "summary_en", err: errors.New(`ent: missing required field "LearningItem.summary_en"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LearningItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := learningitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LearningItem.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DraftRevision(); !ok {
		return &ValidationError{Name: "draft_revision", err: errors.New(`ent: missing required field "LearningItem.draft_revision"`)}
	}
	if _, ok := _c.mutation.PublishedRevision(); !ok {
		return &ValidationError{Name: "published_revision", err: errors.New(`ent: missing required field "LearningItem.published_revision"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LearningItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LearningItem.updated_at"`)}
	}
	return nil
}

func (_c *LearningItemCreate) sqlSave(ctx context.Context) (*LearningItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected LearningItem.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LearningItemCreate) createSpec() (*LearningItem, *sqlgraph.CreateSpec) {
	var (
		_node = &LearningItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(learningitem.Table, sqlgraph.NewFieldSpec(learningitem.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(learningitem.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(learningitem.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.TitleID(); ok {
		_spec.SetField(learningitem.FieldTitleID, field.TypeString, value)
		_node.TitleID = value
	}
	if value, ok := _c.mutation.TitleEn(); ok {
		_spec.SetField(learningitem.FieldTitleEn, field.TypeString, value)
		_node.TitleEn = value
	}
	if value, ok := _c.mutation.SummaryID(); ok {
		_spec.SetField(learningitem.FieldSummaryID, field.TypeString, value)
		_node.SummaryID = value
	}
	if value, ok := _c.mutation.SummaryEn(); ok {
		_spec.SetField(learningitem.FieldSummaryEn, field.TypeString, value)
		_node.SummaryEn = value
	}
	if value, ok := _c.mutation.DocumentJSON(); ok {
		_spec.SetField(learningitem.FieldDocumentJSON, field.TypeJSON, value)
		_node.DocumentJSON = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(learningitem.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DraftRevision(); ok {
		_spec.SetField(learningitem.FieldDraftRevision, field.TypeInt, value)
		_node.DraftRevision = value
	}
	if value, ok := _c.mutation.PublishedRevision(); ok {
		_spec.SetField(learningitem.FieldPublishedRevision, field.TypeInt, value)
		_node.PublishedRevision = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(learningitem.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.ArchivedAt(); ok {
		_spec.SetField(learningitem.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(learningitem.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(learningitem.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(learningitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(learningitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// LearningItemCreateBulk is the builder for creating many LearningItem entities in bulk.
type LearningItemCreateBulk struct {
	config
	err      error
	builders []*LearningItemCreate
}

// Save creates the LearningItem entities in the database.
func (_c *LearningItemCreateBulk) Save(ctx context.Context) ([]*LearningItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LearningItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LearningItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LearningItemCreateBulk) SaveX(ctx context.Context) []*LearningItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LearningItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LearningItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
