// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/notificationdelivery"
)

// NotificationDelivery is the model entity for the NotificationDelivery schema.
type NotificationDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ApprovalRequestID holds the value of the "approval_request_id" field.
	ApprovalRequestID *string `json:"approval_request_id,omitempty"`
	// SupportCaseID holds the value of the "support_case_id" field.
	SupportCaseID *string `json:"support_case_id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel notificationdelivery.Channel `json:"channel,omitempty"`
	// Recipient holds the value of the "recipient" field.
	Recipient string `json:"recipient,omitempty"`
	// Status holds the value of the "status" field.
	Status notificationdelivery.Status `json:"status,omitempty"`
	// ProviderMessageID holds the value of the "provider_message_id" field.
	ProviderMessageID *string `json:"provider_message_id,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationdelivery.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case notificationdelivery.FieldID, notificationdelivery.FieldApprovalRequestID, notificationdelivery.FieldSupportCaseID, notificationdelivery.FieldChannel, notificationdelivery.FieldRecipient, notificationdelivery.FieldStatus, notificationdelivery.FieldProviderMessageID, notificationdelivery.FieldErrorCode:
			values[i] = new(sql.NullString)
		case notificationdelivery.FieldCreatedAt, notificationdelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationDelivery fields.
func (_m *NotificationDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationdelivery.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case notificationdelivery.FieldApprovalRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approval_request_id", values[i])
			} else if value.Valid {
				_m.ApprovalRequestID = new(string)
				*_m.ApprovalRequestID = value.String
			}
		case notificationdelivery.FieldSupportCaseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field support_case_id", values[i])
			} else if value.Valid {
				_m.SupportCaseID = new(string)
				*_m.SupportCaseID = value.String
			}
		case notificationdelivery.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = notificationdelivery.Channel(value.String)
			}
		case notificationdelivery.FieldRecipient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient", values[i])
			} else if value.Valid {
				_m.Recipient = value.String
			}
		case notificationdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = notificationdelivery.Status(value.String)
			}
		case notificationdelivery.FieldProviderMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_message_id", values[i])
			} else if value.Valid {
				_m.ProviderMessageID = new(string)
				*_m.ProviderMessageID = value.String
			}
		case notificationdelivery.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case notificationdelivery.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case notificationdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationdelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationDelivery.
// Note that you need to call NotificationDelivery.Unwrap() before calling this method if this NotificationDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationDelivery) Update() *NotificationDeliveryUpdateOne {
	return NewNotificationDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationDelivery) Unwrap() *NotificationDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ApprovalRequestID; v != nil {
		builder.WriteString("approval_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SupportCaseID; v != nil {
		builder.WriteString("support_case_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Channel))
	builder.WriteString(", ")
	builder.WriteString("recipient=")
	builder.WriteString(_m.Recipient)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ProviderMessageID; v != nil {
		builder.WriteString("provider_message_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationDeliveries is a parsable slice of NotificationDelivery.
type NotificationDeliveries []*NotificationDelivery
