// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/recoverypracticesession"
)

// RecoveryPracticeSessionUpdate is the builder for updating RecoveryPracticeSession entities.
type RecoveryPracticeSessionUpdate struct {
	config
	hooks    []Hook
	mutation *RecoveryPracticeSessionMutation
}

// Where appends a list predicates to the RecoveryPracticeSessionUpdate builder.
func (_u *RecoveryPracticeSessionUpdate) Where(ps ...predicate.RecoveryPracticeSession) *RecoveryPracticeSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RecoveryPracticeSessionUpdate) SetUserID(v string) *RecoveryPracticeSessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdate) SetNillableUserID(v *string) *RecoveryPracticeSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPracticeKind sets the "practice_kind" field.
func (_u *RecoveryPracticeSessionUpdate) SetPracticeKind(v recoverypracticesession.PracticeKind) *RecoveryPracticeSessionUpdate {
	_u.mutation.SetPracticeKind(v)
	return _u
}

// SetNillablePracticeKind sets the "practice_kind" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdate) SetNillablePracticeKind(v *recoverypracticesession.PracticeKind) *RecoveryPracticeSessionUpdate {
	if v != nil {
		_u.SetPracticeKind(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *RecoveryPracticeSessionUpdate) SetDurationSeconds(v int) *RecoveryPracticeSessionUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdate) SetNillableDurationSeconds(v *int) *RecoveryPracticeSessionUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *RecoveryPracticeSessionUpdate) AddDurationSeconds(v int) *RecoveryPracticeSessionUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *RecoveryPracticeSessionUpdate) SetFeedback(v recoverypracticesession.Feedback) *RecoveryPracticeSessionUpdate {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdate) SetNillableFeedback(v *recoverypracticesession.Feedback) *RecoveryPracticeSessionUpdate {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *RecoveryPracticeSessionUpdate) ClearFeedback() *RecoveryPracticeSessionUpdate {
	_u.mutation.ClearFeedback()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RecoveryPracticeSessionUpdate) SetCompletedAt(v time.Time) *RecoveryPracticeSessionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdate) SetNillableCompletedAt(v *time.Time) *RecoveryPracticeSessionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// Mutation returns the RecoveryPracticeSessionMutation object of the builder.
func (_u *RecoveryPracticeSessionUpdate) Mutation() *RecoveryPracticeSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecoveryPracticeSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecoveryPracticeSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecoveryPracticeSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecoveryPracticeSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecoveryPracticeSessionUpdate) check() error {
	if v, ok := _u.mutation.PracticeKind(); ok {
		if err := recoverypracticesession.PracticeKindValidator(v); err != nil {
			return &ValidationError{Name: "practice_kind", err: fmt.Errorf(`ent: validator failed for field "RecoveryPracticeSession.practice_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSeconds(); ok {
		if err := recoverypracticesession.DurationSecondsValidator(v); err != nil {
			return &ValidationError{Name: "duration_seconds", err: fmt.Errorf(`ent: validator failed for field "RecoveryPracticeSession.duration_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Feedback(); ok {
		if err := recoverypracticesession.FeedbackValidator(v); err != nil {
			return &ValidationError{Name: "feedback", err: fmt.Errorf(`ent: validator failed for field "RecoveryPracticeSession.feedback": %w`, err)}
		}
	}
	return nil
}

func (_u *RecoveryPracticeSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recoverypracticesession.Table, recoverypracticesession.Columns, sqlgraph.NewFieldSpec(recoverypracticesession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(recoverypracticesession.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PracticeKind(); ok {
		_spec.SetField(recoverypracticesession.FieldPracticeKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(recoverypracticesession.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(recoverypracticesession.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(recoverypracticesession.FieldFeedback, field.TypeEnum, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(recoverypracticesession.FieldFeedback, field.TypeEnum)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(recoverypracticesession.FieldCompletedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recoverypracticesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecoveryPracticeSessionUpdateOne is the builder for updating a single RecoveryPracticeSession entity.
type RecoveryPracticeSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecoveryPracticeSessionMutation
}

// SetUserID sets the "user_id" field.
func (_u *RecoveryPracticeSessionUpdateOne) SetUserID(v string) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdateOne) SetNillableUserID(v *string) *RecoveryPracticeSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPracticeKind sets the "practice_kind" field.
func (_u *RecoveryPracticeSessionUpdateOne) SetPracticeKind(v recoverypracticesession.PracticeKind) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.SetPracticeKind(v)
	return _u
}

// SetNillablePracticeKind sets the "practice_kind" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdateOne) SetNillablePracticeKind(v *recoverypracticesession.PracticeKind) *RecoveryPracticeSessionUpdateOne {
	if v != nil {
		_u.SetPracticeKind(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *RecoveryPracticeSessionUpdateOne) SetDurationSeconds(v int) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdateOne) SetNillableDurationSeconds(v *int) *RecoveryPracticeSessionUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *RecoveryPracticeSessionUpdateOne) AddDurationSeconds(v int) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *RecoveryPracticeSessionUpdateOne) SetFeedback(v recoverypracticesession.Feedback) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdateOne) SetNillableFeedback(v *recoverypracticesession.Feedback) *RecoveryPracticeSessionUpdateOne {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *RecoveryPracticeSessionUpdateOne) ClearFeedback() *RecoveryPracticeSessionUpdateOne {
	_u.mutation.ClearFeedback()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RecoveryPracticeSessionUpdateOne) SetCompletedAt(v time.Time) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RecoveryPracticeSessionUpdateOne) SetNillableCompletedAt(v *time.Time) *RecoveryPracticeSessionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// Mutation returns the RecoveryPracticeSessionMutation object of the builder.
func (_u *RecoveryPracticeSessionUpdateOne) Mutation() *RecoveryPracticeSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RecoveryPracticeSessionUpdate builder.
func (_u *RecoveryPracticeSessionUpdateOne) Where(ps ...predicate.RecoveryPracticeSession) *RecoveryPracticeSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecoveryPracticeSessionUpdateOne) Select(field string, fields ...string) *RecoveryPracticeSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecoveryPracticeSession entity.
func (_u *RecoveryPracticeSessionUpdateOne) Save(ctx context.Context) (*RecoveryPracticeSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecoveryPracticeSessionUpdateOne) SaveX(ctx context.Context) *RecoveryPracticeSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecoveryPracticeSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecoveryPracticeSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecoveryPracticeSessionUpdateOne) check() error {
	if v, ok := _u.mutation.PracticeKind(); ok {
		if err := recoverypracticesession.PracticeKindValidator(v); err != nil {
			return &ValidationError{Name: "practice_kind", err: fmt.Errorf(`ent: validator failed for field "RecoveryPracticeSession.practice_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSeconds(); ok {
		if err := recoverypracticesession.DurationSecondsValidator(v); err != nil {
			return &ValidationError{Name: "duration_seconds", err: fmt.Errorf(`ent: validator failed for field "RecoveryPracticeSession.duration_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Feedback(); ok {
		if err := recoverypracticesession.FeedbackValidator(v); err != nil {
			return &ValidationError{Name: "feedback", err: fmt.Errorf(`ent: validator failed for field "RecoveryPracticeSession.feedback": %w`, err)}
		}
	}
	return nil
}

func (_u *RecoveryPracticeSessionUpdateOne) sqlSave(ctx context.Context) (_node *RecoveryPracticeSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recoverypracticesession.Table, recoverypracticesession.Columns, sqlgraph.NewFieldSpec(recoverypracticesession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecoveryPracticeSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recoverypracticesession.FieldID)
		for _, f := range fields {
			if !recoverypracticesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recoverypracticesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(recoverypracticesession.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PracticeKind(); ok {
		_spec.SetField(recoverypracticesession.FieldPracticeKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(recoverypracticesession.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(recoverypracticesession.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(recoverypracticesession.FieldFeedback, field.TypeEnum, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(recoverypracticesession.FieldFeedback, field.TypeEnum)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(recoverypracticesession.FieldCompletedAt, field.TypeTime, value)
	}
	_node = &RecoveryPracticeSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recoverypracticesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
