// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/releasecohort"
)

// ReleaseCohort is the model entity for the ReleaseCohort schema.
type ReleaseCohort struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RolloutID holds the value of the "rollout_id" field.
	RolloutID string `json:"rollout_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform releasecohort.Platform `json:"platform,omitempty"`
	// Percentage holds the value of the "percentage" field.
	Percentage int `json:"percentage,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *string `json:"organization_id,omitempty"`
	// AppVersionConstraint holds the value of the "app_version_constraint" field.
	AppVersionConstraint *string `json:"app_version_constraint,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReleaseCohort) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case releasecohort.FieldPercentage:
			values[i] = new(sql.NullInt64)
		case releasecohort.FieldID, releasecohort.FieldRolloutID, releasecohort.FieldPlatform, releasecohort.FieldOrganizationID, releasecohort.FieldAppVersionConstraint:
			values[i] = new(sql.NullString)
		case releasecohort.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReleaseCohort fields.
func (_m *ReleaseCohort) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case releasecohort.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case releasecohort.FieldRolloutID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rollout_id", values[i])
			} else if value.Valid {
				_m.RolloutID = value.String
			}
		case releasecohort.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = releasecohort.Platform(value.String)
			}
		case releasecohort.FieldPercentage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field percentage", values[i])
			} else if value.Valid {
				_m.Percentage = int(value.Int64)
			}
		case releasecohort.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(string)
				*_m.OrganizationID = value.String
			}
		case releasecohort.FieldAppVersionConstraint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_version_constraint", values[i])
			} else if value.Valid {
				_m.AppVersionConstraint = new(string)
				*_m.AppVersionConstraint = value.String
			}
		case releasecohort.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReleaseCohort.
// This includes values selected through modifiers, order, etc.
func (_m *ReleaseCohort) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReleaseCohort.
// Note that you need to call ReleaseCohort.Unwrap() before calling this method if this ReleaseCohort
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReleaseCohort) Update() *ReleaseCohortUpdateOne {
	return NewReleaseCohortClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReleaseCohort entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReleaseCohort) Unwrap() *ReleaseCohort {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReleaseCohort is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReleaseCohort) String() string {
	var builder strings.Builder
	builder.WriteString("ReleaseCohort(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rollout_id=")
	builder.WriteString(_m.RolloutID)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("percentage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Percentage))
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AppVersionConstraint; v != nil {
		builder.WriteString("app_version_constraint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReleaseCohorts is a parsable slice of ReleaseCohort.
type ReleaseCohorts []*ReleaseCohort
