// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/releasecohort"
)

// ReleaseCohortUpdate is the builder for updating ReleaseCohort entities.
type ReleaseCohortUpdate struct {
	config
	hooks    []Hook
	mutation *ReleaseCohortMutation
}

// Where appends a list predicates to the ReleaseCohortUpdate builder.
func (_u *ReleaseCohortUpdate) Where(ps ...predicate.ReleaseCohort) *ReleaseCohortUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRolloutID sets the "rollout_id" field.
func (_u *ReleaseCohortUpdate) SetRolloutID(v string) *ReleaseCohortUpdate {
	_u.mutation.SetRolloutID(v)
	return _u
}

// SetNillableRolloutID sets the "rollout_id" field if the given value is not nil.
func (_u *ReleaseCohortUpdate) SetNillableRolloutID(v *string) *ReleaseCohortUpdate {
	if v != nil {
		_u.SetRolloutID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ReleaseCohortUpdate) SetPlatform(v releasecohort.Platform) *ReleaseCohortUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ReleaseCohortUpdate) SetNillablePlatform(v *releasecohort.Platform) *ReleaseCohortUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPercentage sets the "percentage" field.
func (_u *ReleaseCohortUpdate) SetPercentage(v int) *ReleaseCohortUpdate {
	_u.mutation.ResetPercentage()
	_u.mutation.SetPercentage(v)
	return _u
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_u *ReleaseCohortUpdate) SetNillablePercentage(v *int) *ReleaseCohortUpdate {
	if v != nil {
		_u.SetPercentage(*v)
	}
	return _u
}

// AddPercentage adds value to the "percentage" field.
func (_u *ReleaseCohortUpdate) AddPercentage(v int) *ReleaseCohortUpdate {
	_u.mutation.AddPercentage(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *ReleaseCohortUpdate) SetOrganizationID(v string) *ReleaseCohortUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *ReleaseCohortUpdate) SetNillableOrganizationID(v *string) *ReleaseCohortUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *ReleaseCohortUpdate) ClearOrganizationID() *ReleaseCohortUpdate {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetAppVersionConstraint sets the "app_version_constraint" field.
func (_u *ReleaseCohortUpdate) SetAppVersionConstraint(v string) *ReleaseCohortUpdate {
	_u.mutation.SetAppVersionConstraint(v)
	return _u
}

// SetNillableAppVersionConstraint sets the "app_version_constraint" field if the given value is not nil.
func (_u *ReleaseCohortUpdate) SetNillableAppVersionConstraint(v *string) *ReleaseCohortUpdate {
	if v != nil {
		_u.SetAppVersionConstraint(*v)
	}
	return _u
}

// ClearAppVersionConstraint clears the value of the "app_version_constraint" field.
func (_u *ReleaseCohortUpdate) ClearAppVersionConstraint() *ReleaseCohortUpdate {
	_u.mutation.ClearAppVersionConstraint()
	return _u
}

// Mutation returns the ReleaseCohortMutation object of the builder.
func (_u *ReleaseCohortUpdate) Mutation() *ReleaseCohortMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReleaseCohortUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReleaseCohortUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReleaseCohortUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReleaseCohortUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReleaseCohortUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := releasecohort.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ReleaseCohort.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *ReleaseCohortUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(releasecohort.Table, releasecohort.Columns, sqlgraph.NewFieldSpec(releasecohort.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RolloutID(); ok {
		_spec.SetField(releasecohort.FieldRolloutID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(releasecohort.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Percentage(); ok {
		_spec.SetField(releasecohort.FieldPercentage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPercentage(); ok {
		_spec.AddField(releasecohort.FieldPercentage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(releasecohort.FieldOrganizationID, field.TypeString, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(releasecohort.FieldOrganizationID, field.TypeString)
	}
	if value, ok := _u.mutation.AppVersionConstraint(); ok {
		_spec.SetField(releasecohort.FieldAppVersionConstraint, field.TypeString, value)
	}
	if _u.mutation.AppVersionConstraintCleared() {
		_spec.ClearField(releasecohort.FieldAppVersionConstraint, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{releasecohort.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReleaseCohortUpdateOne is the builder for updating a single ReleaseCohort entity.
type ReleaseCohortUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReleaseCohortMutation
}

// SetRolloutID sets the "rollout_id" field.
func (_u *ReleaseCohortUpdateOne) SetRolloutID(v string) *ReleaseCohortUpdateOne {
	_u.mutation.SetRolloutID(v)
	return _u
}

// SetNillableRolloutID sets the "rollout_id" field if the given value is not nil.
func (_u *ReleaseCohortUpdateOne) SetNillableRolloutID(v *string) *ReleaseCohortUpdateOne {
	if v != nil {
		_u.SetRolloutID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ReleaseCohortUpdateOne) SetPlatform(v releasecohort.Platform) *ReleaseCohortUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ReleaseCohortUpdateOne) SetNillablePlatform(v *releasecohort.Platform) *ReleaseCohortUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPercentage sets the "percentage" field.
func (_u *ReleaseCohortUpdateOne) SetPercentage(v int) *ReleaseCohortUpdateOne {
	_u.mutation.ResetPercentage()
	_u.mutation.SetPercentage(v)
	return _u
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_u *ReleaseCohortUpdateOne) SetNillablePercentage(v *int) *ReleaseCohortUpdateOne {
	if v != nil {
		_u.SetPercentage(*v)
	}
	return _u
}

// AddPercentage adds value to the "percentage" field.
func (_u *ReleaseCohortUpdateOne) AddPercentage(v int) *ReleaseCohortUpdateOne {
	_u.mutation.AddPercentage(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *ReleaseCohortUpdateOne) SetOrganizationID(v string) *ReleaseCohortUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *ReleaseCohortUpdateOne) SetNillableOrganizationID(v *string) *ReleaseCohortUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *ReleaseCohortUpdateOne) ClearOrganizationID() *ReleaseCohortUpdateOne {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetAppVersionConstraint sets the "app_version_constraint" field.
func (_u *ReleaseCohortUpdateOne) SetAppVersionConstraint(v string) *ReleaseCohortUpdateOne {
	_u.mutation.SetAppVersionConstraint(v)
	return _u
}

// SetNillableAppVersionConstraint sets the "app_version_constraint" field if the given value is not nil.
func (_u *ReleaseCohortUpdateOne) SetNillableAppVersionConstraint(v *string) *ReleaseCohortUpdateOne {
	if v != nil {
		_u.SetAppVersionConstraint(*v)
	}
	return _u
}

// ClearAppVersionConstraint clears the value of the "app_version_constraint" field.
func (_u *ReleaseCohortUpdateOne) ClearAppVersionConstraint() *ReleaseCohortUpdateOne {
	_u.mutation.ClearAppVersionConstraint()
	return _u
}

// Mutation returns the ReleaseCohortMutation object of the builder.
func (_u *ReleaseCohortUpdateOne) Mutation() *ReleaseCohortMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReleaseCohortUpdate builder.
func (_u *ReleaseCohortUpdateOne) Where(ps ...predicate.ReleaseCohort) *ReleaseCohortUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReleaseCohortUpdateOne) Select(field string, fields ...string) *ReleaseCohortUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReleaseCohort entity.
func (_u *ReleaseCohortUpdateOne) Save(ctx context.Context) (*ReleaseCohort, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReleaseCohortUpdateOne) SaveX(ctx context.Context) *ReleaseCohort {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReleaseCohortUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReleaseCohortUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReleaseCohortUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := releasecohort.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ReleaseCohort.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *ReleaseCohortUpdateOne) sqlSave(ctx context.Context) (_node *ReleaseCohort, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(releasecohort.Table, releasecohort.Columns, sqlgraph.NewFieldSpec(releasecohort.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReleaseCohort.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, releasecohort.FieldID)
		for _, f := range fields {
			if !releasecohort.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != releasecohort.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RolloutID(); ok {
		_spec.SetField(releasecohort.FieldRolloutID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(releasecohort.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Percentage(); ok {
		_spec.SetField(releasecohort.FieldPercentage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPercentage(); ok {
		_spec.AddField(releasecohort.FieldPercentage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(releasecohort.FieldOrganizationID, field.TypeString, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(releasecohort.FieldOrganizationID, field.TypeString)
	}
	if value, ok := _u.mutation.AppVersionConstraint(); ok {
		_spec.SetField(releasecohort.FieldAppVersionConstraint, field.TypeString, value)
	}
	if _u.mutation.AppVersionConstraintCleared() {
		_spec.ClearField(releasecohort.FieldAppVersionConstraint, field.TypeString)
	}
	_node = &ReleaseCohort{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{releasecohort.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
