// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/supportcase"
)

// SupportCaseUpdate is the builder for updating SupportCase entities.
type SupportCaseUpdate struct {
	config
	hooks    []Hook
	mutation *SupportCaseMutation
}

// Where appends a list predicates to the SupportCaseUpdate builder.
func (_u *SupportCaseUpdate) Where(ps ...predicate.SupportCase) *SupportCaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportCaseUpdate) SetUserID(v string) *SupportCaseUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportCaseUpdate) SetNillableUserID(v *string) *SupportCaseUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *SupportCaseUpdate) SetOrganizationID(v string) *SupportCaseUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *SupportCaseUpdate) SetNillableOrganizationID(v *string) *SupportCaseUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *SupportCaseUpdate) ClearOrganizationID() *SupportCaseUpdate {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetType sets the "type" field.
func (_u *SupportCaseUpdate) SetType(v supportcase.Type) *SupportCaseUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SupportCaseUpdate) SetNillableType(v *supportcase.Type) *SupportCaseUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportCaseUpdate) SetStatus(v supportcase.Status) *SupportCaseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportCaseUpdate) SetNillableStatus(v *supportcase.Status) *SupportCaseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportCaseUpdate) SetPriority(v supportcase.Priority) *SupportCaseUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportCaseUpdate) SetNillablePriority(v *supportcase.Priority) *SupportCaseUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SupportCaseUpdate) SetSummary(v string) *SupportCaseUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SupportCaseUpdate) SetNillableSummary(v *string) *SupportCaseUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportCaseUpdate) SetUpdatedAt(v time.Time) *SupportCaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportCaseMutation object of the builder.
func (_u *SupportCaseUpdate) Mutation() *SupportCaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportCaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportCaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportCaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportCaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportCaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportcase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportCaseUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := supportcase.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportCase.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportcase.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportCase.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportcase.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportCase.priority": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportCaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportcase.Table, supportcase.Columns, sqlgraph.NewFieldSpec(supportcase.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportcase.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(supportcase.FieldOrganizationID, field.TypeString, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(supportcase.FieldOrganizationID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(supportcase.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportcase.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportcase.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(supportcase.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportcase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportcase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportCaseUpdateOne is the builder for updating a single SupportCase entity.
type SupportCaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportCaseMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupportCaseUpdateOne) SetUserID(v string) *SupportCaseUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportCaseUpdateOne) SetNillableUserID(v *string) *SupportCaseUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *SupportCaseUpdateOne) SetOrganizationID(v string) *SupportCaseUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *SupportCaseUpdateOne) SetNillableOrganizationID(v *string) *SupportCaseUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *SupportCaseUpdateOne) ClearOrganizationID() *SupportCaseUpdateOne {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetType sets the "type" field.
func (_u *SupportCaseUpdateOne) SetType(v supportcase.Type) *SupportCaseUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SupportCaseUpdateOne) SetNillableType(v *supportcase.Type) *SupportCaseUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportCaseUpdateOne) SetStatus(v supportcase.Status) *SupportCaseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportCaseUpdateOne) SetNillableStatus(v *supportcase.Status) *SupportCaseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportCaseUpdateOne) SetPriority(v supportcase.Priority) *SupportCaseUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportCaseUpdateOne) SetNillablePriority(v *supportcase.Priority) *SupportCaseUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SupportCaseUpdateOne) SetSummary(v string) *SupportCaseUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SupportCaseUpdateOne) SetNillableSummary(v *string) *SupportCaseUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportCaseUpdateOne) SetUpdatedAt(v time.Time) *SupportCaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportCaseMutation object of the builder.
func (_u *SupportCaseUpdateOne) Mutation() *SupportCaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportCaseUpdate builder.
func (_u *SupportCaseUpdateOne) Where(ps ...predicate.SupportCase) *SupportCaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportCaseUpdateOne) Select(field string, fields ...string) *SupportCaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportCase entity.
func (_u *SupportCaseUpdateOne) Save(ctx context.Context) (*SupportCase, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportCaseUpdateOne) SaveX(ctx context.Context) *SupportCase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportCaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportCaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportCaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportcase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportCaseUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := supportcase.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportCase.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportcase.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportCase.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportcase.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportCase.priority": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportCaseUpdateOne) sqlSave(ctx context.Context) (_node *SupportCase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportcase.Table, supportcase.Columns, sqlgraph.NewFieldSpec(supportcase.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportCase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportcase.FieldID)
		for _, f := range fields {
			if !supportcase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportcase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportcase.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(supportcase.FieldOrganizationID, field.TypeString, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(supportcase.FieldOrganizationID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(supportcase.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportcase.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportcase.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(supportcase.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportcase.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SupportCase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportcase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
