// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/supportactionaudit"
)

// SupportActionAuditDelete is the builder for deleting a SupportActionAudit entity.
type SupportActionAuditDelete struct {
	config
	hooks    []Hook
	mutation *SupportActionAuditMutation
}

// Where appends a list predicates to the SupportActionAuditDelete builder.
func (_d *SupportActionAuditDelete) Where(ps ...predicate.SupportActionAudit) *SupportActionAuditDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SupportActionAuditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SupportActionAuditDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SupportActionAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(supportactionaudit.Table, sqlgraph.NewFieldSpec(supportactionaudit.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SupportActionAuditDeleteOne is the builder for deleting a single SupportActionAudit entity.
type SupportActionAuditDeleteOne struct {
	_d *SupportActionAuditDelete
}

// Where appends a list predicates to the SupportActionAuditDelete builder.
func (_d *SupportActionAuditDeleteOne) Where(ps ...predicate.SupportActionAudit) *SupportActionAuditDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SupportActionAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{supportactionaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SupportActionAuditDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
