// Code generated by ent, DO NOT EDIT.

package modelrollout

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelrollout type in the database.
	Label = "model_rollout"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelReleaseID holds the string denoting the model_release_id field in the database.
	FieldModelReleaseID = "model_release_id"
	// FieldRulesetReleaseID holds the string denoting the ruleset_release_id field in the database.
	FieldRulesetReleaseID = "ruleset_release_id"
	// FieldNetworkRulesetReleaseID holds the string denoting the network_ruleset_release_id field in the database.
	FieldNetworkRulesetReleaseID = "network_ruleset_release_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCohortJSON holds the string denoting the cohort_json field in the database.
	FieldCohortJSON = "cohort_json"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelrollout in the database.
	Table = "model_rollouts"
)

// Columns holds all SQL columns for modelrollout fields.
var Columns = []string{
	FieldID,
	FieldModelReleaseID,
	FieldRulesetReleaseID,
	FieldNetworkRulesetReleaseID,
	FieldStatus,
	FieldCohortJSON,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusDraft is the default value of the Status enum.
const DefaultStatus = StatusDraft

// Status values.
const (
	StatusDraft      Status = "draft"
	StatusStaged     Status = "staged"
	StatusActive     Status = "active"
	StatusPaused     Status = "paused"
	StatusRolledBack Status = "rolled_back"
	StatusCompleted  Status = "completed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusStaged, StatusActive, StatusPaused, StatusRolledBack, StatusCompleted:
		return nil
	default:
		return fmt.Errorf("modelrollout: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ModelRollout queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelReleaseID orders the results by the model_release_id field.
func ByModelReleaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelReleaseID, opts...).ToFunc()
}

// ByRulesetReleaseID orders the results by the ruleset_release_id field.
func ByRulesetReleaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRulesetReleaseID, opts...).ToFunc()
}

// ByNetworkRulesetReleaseID orders the results by the network_ruleset_release_id field.
func ByNetworkRulesetReleaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetworkRulesetReleaseID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
