// Code generated by ent, DO NOT EDIT.

package modelrollout

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContainsFold(FieldID, id))
}

// ModelReleaseID applies equality check predicate on the "model_release_id" field. It's identical to ModelReleaseIDEQ.
func ModelReleaseID(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldModelReleaseID, v))
}

// RulesetReleaseID applies equality check predicate on the "ruleset_release_id" field. It's identical to RulesetReleaseIDEQ.
func RulesetReleaseID(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldRulesetReleaseID, v))
}

// NetworkRulesetReleaseID applies equality check predicate on the "network_ruleset_release_id" field. It's identical to NetworkRulesetReleaseIDEQ.
func NetworkRulesetReleaseID(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldNetworkRulesetReleaseID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelReleaseIDEQ applies the EQ predicate on the "model_release_id" field.
func ModelReleaseIDEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldModelReleaseID, v))
}

// ModelReleaseIDNEQ applies the NEQ predicate on the "model_release_id" field.
func ModelReleaseIDNEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldModelReleaseID, v))
}

// ModelReleaseIDIn applies the In predicate on the "model_release_id" field.
func ModelReleaseIDIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldModelReleaseID, vs...))
}

// ModelReleaseIDNotIn applies the NotIn predicate on the "model_release_id" field.
func ModelReleaseIDNotIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldModelReleaseID, vs...))
}

// ModelReleaseIDGT applies the GT predicate on the "model_release_id" field.
func ModelReleaseIDGT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldModelReleaseID, v))
}

// ModelReleaseIDGTE applies the GTE predicate on the "model_release_id" field.
func ModelReleaseIDGTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldModelReleaseID, v))
}

// ModelReleaseIDLT applies the LT predicate on the "model_release_id" field.
func ModelReleaseIDLT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldModelReleaseID, v))
}

// ModelReleaseIDLTE applies the LTE predicate on the "model_release_id" field.
func ModelReleaseIDLTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldModelReleaseID, v))
}

// ModelReleaseIDContains applies the Contains predicate on the "model_release_id" field.
func ModelReleaseIDContains(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContains(FieldModelReleaseID, v))
}

// ModelReleaseIDHasPrefix applies the HasPrefix predicate on the "model_release_id" field.
func ModelReleaseIDHasPrefix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasPrefix(FieldModelReleaseID, v))
}

// ModelReleaseIDHasSuffix applies the HasSuffix predicate on the "model_release_id" field.
func ModelReleaseIDHasSuffix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasSuffix(FieldModelReleaseID, v))
}

// ModelReleaseIDIsNil applies the IsNil predicate on the "model_release_id" field.
func ModelReleaseIDIsNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIsNull(FieldModelReleaseID))
}

// ModelReleaseIDNotNil applies the NotNil predicate on the "model_release_id" field.
func ModelReleaseIDNotNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotNull(FieldModelReleaseID))
}

// ModelReleaseIDEqualFold applies the EqualFold predicate on the "model_release_id" field.
func ModelReleaseIDEqualFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEqualFold(FieldModelReleaseID, v))
}

// ModelReleaseIDContainsFold applies the ContainsFold predicate on the "model_release_id" field.
func ModelReleaseIDContainsFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContainsFold(FieldModelReleaseID, v))
}

// RulesetReleaseIDEQ applies the EQ predicate on the "ruleset_release_id" field.
func RulesetReleaseIDEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDNEQ applies the NEQ predicate on the "ruleset_release_id" field.
func RulesetReleaseIDNEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDIn applies the In predicate on the "ruleset_release_id" field.
func RulesetReleaseIDIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldRulesetReleaseID, vs...))
}

// RulesetReleaseIDNotIn applies the NotIn predicate on the "ruleset_release_id" field.
func RulesetReleaseIDNotIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldRulesetReleaseID, vs...))
}

// RulesetReleaseIDGT applies the GT predicate on the "ruleset_release_id" field.
func RulesetReleaseIDGT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDGTE applies the GTE predicate on the "ruleset_release_id" field.
func RulesetReleaseIDGTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDLT applies the LT predicate on the "ruleset_release_id" field.
func RulesetReleaseIDLT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDLTE applies the LTE predicate on the "ruleset_release_id" field.
func RulesetReleaseIDLTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDContains applies the Contains predicate on the "ruleset_release_id" field.
func RulesetReleaseIDContains(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContains(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDHasPrefix applies the HasPrefix predicate on the "ruleset_release_id" field.
func RulesetReleaseIDHasPrefix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasPrefix(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDHasSuffix applies the HasSuffix predicate on the "ruleset_release_id" field.
func RulesetReleaseIDHasSuffix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasSuffix(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDIsNil applies the IsNil predicate on the "ruleset_release_id" field.
func RulesetReleaseIDIsNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIsNull(FieldRulesetReleaseID))
}

// RulesetReleaseIDNotNil applies the NotNil predicate on the "ruleset_release_id" field.
func RulesetReleaseIDNotNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotNull(FieldRulesetReleaseID))
}

// RulesetReleaseIDEqualFold applies the EqualFold predicate on the "ruleset_release_id" field.
func RulesetReleaseIDEqualFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEqualFold(FieldRulesetReleaseID, v))
}

// RulesetReleaseIDContainsFold applies the ContainsFold predicate on the "ruleset_release_id" field.
func RulesetReleaseIDContainsFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContainsFold(FieldRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDEQ applies the EQ predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDNEQ applies the NEQ predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDNEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDIn applies the In predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldNetworkRulesetReleaseID, vs...))
}

// NetworkRulesetReleaseIDNotIn applies the NotIn predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDNotIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldNetworkRulesetReleaseID, vs...))
}

// NetworkRulesetReleaseIDGT applies the GT predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDGT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDGTE applies the GTE predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDGTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDLT applies the LT predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDLT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDLTE applies the LTE predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDLTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDContains applies the Contains predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDContains(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContains(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDHasPrefix applies the HasPrefix predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDHasPrefix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasPrefix(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDHasSuffix applies the HasSuffix predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDHasSuffix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasSuffix(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDIsNil applies the IsNil predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDIsNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIsNull(FieldNetworkRulesetReleaseID))
}

// NetworkRulesetReleaseIDNotNil applies the NotNil predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDNotNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotNull(FieldNetworkRulesetReleaseID))
}

// NetworkRulesetReleaseIDEqualFold applies the EqualFold predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDEqualFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEqualFold(FieldNetworkRulesetReleaseID, v))
}

// NetworkRulesetReleaseIDContainsFold applies the ContainsFold predicate on the "network_ruleset_release_id" field.
func NetworkRulesetReleaseIDContainsFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContainsFold(FieldNetworkRulesetReleaseID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldStatus, vs...))
}

// CohortJSONIsNil applies the IsNil predicate on the "cohort_json" field.
func CohortJSONIsNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIsNull(FieldCohortJSON))
}

// CohortJSONNotNil applies the NotNil predicate on the "cohort_json" field.
func CohortJSONNotNil() predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotNull(FieldCohortJSON))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelRollout {
	return predicate.ModelRollout(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelRollout) predicate.ModelRollout {
	return predicate.ModelRollout(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelRollout) predicate.ModelRollout {
	return predicate.ModelRollout(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelRollout) predicate.ModelRollout {
	return predicate.ModelRollout(sql.NotPredicates(p))
}
