// Code generated by ent, DO NOT EDIT.

package recoverypracticesession

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the recoverypracticesession type in the database.
	Label = "recovery_practice_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPracticeKind holds the string denoting the practice_kind field in the database.
	FieldPracticeKind = "practice_kind"
	// FieldDurationSeconds holds the string denoting the duration_seconds field in the database.
	FieldDurationSeconds = "duration_seconds"
	// FieldFeedback holds the string denoting the feedback field in the database.
	FieldFeedback = "feedback"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the recoverypracticesession in the database.
	Table = "recovery_practice_sessions"
)

// Columns holds all SQL columns for recoverypracticesession fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPracticeKind,
	FieldDurationSeconds,
	FieldFeedback,
	FieldCompletedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DurationSecondsValidator is a validator for the "duration_seconds" field. It is called by the builders before save.
	DurationSecondsValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// PracticeKind defines the type for the "practice_kind" enum field.
type PracticeKind string

// PracticeKind values.
const (
	PracticeKindUrgeSurfing    PracticeKind = "urge_surfing"
	PracticeKindGrounding54321 PracticeKind = "grounding_54321"
	PracticeKindFocusSprint    PracticeKind = "focus_sprint"
)

func (pk PracticeKind) String() string {
	return string(pk)
}

// PracticeKindValidator is a validator for the "practice_kind" field enum values. It is called by the builders before save.
func PracticeKindValidator(pk PracticeKind) error {
	switch pk {
	case PracticeKindUrgeSurfing, PracticeKindGrounding54321, PracticeKindFocusSprint:
		return nil
	default:
		return fmt.Errorf("recoverypracticesession: invalid enum value for practice_kind field: %q", pk)
	}
}

// Feedback defines the type for the "feedback" enum field.
type Feedback string

// Feedback values.
const (
	FeedbackLighter      Feedback = "lighter"
	FeedbackSame         Feedback = "same"
	FeedbackHeavier      Feedback = "heavier"
	FeedbackPreferNotSay Feedback = "prefer_not_say"
)

func (f Feedback) String() string {
	return string(f)
}

// FeedbackValidator is a validator for the "feedback" field enum values. It is called by the builders before save.
func FeedbackValidator(f Feedback) error {
	switch f {
	case FeedbackLighter, FeedbackSame, FeedbackHeavier, FeedbackPreferNotSay:
		return nil
	default:
		return fmt.Errorf("recoverypracticesession: invalid enum value for feedback field: %q", f)
	}
}

// OrderOption defines the ordering options for the RecoveryPracticeSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPracticeKind orders the results by the practice_kind field.
func ByPracticeKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPracticeKind, opts...).ToFunc()
}

// ByDurationSeconds orders the results by the duration_seconds field.
func ByDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSeconds, opts...).ToFunc()
}

// ByFeedback orders the results by the feedback field.
func ByFeedback(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedback, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
