// Code generated by ent, DO NOT EDIT.

package recoverypracticesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gamblock-ai/gamblock-ai-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldUserID, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldDurationSeconds, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldContainsFold(FieldUserID, v))
}

// PracticeKindEQ applies the EQ predicate on the "practice_kind" field.
func PracticeKindEQ(v PracticeKind) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldPracticeKind, v))
}

// PracticeKindNEQ applies the NEQ predicate on the "practice_kind" field.
func PracticeKindNEQ(v PracticeKind) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldPracticeKind, v))
}

// PracticeKindIn applies the In predicate on the "practice_kind" field.
func PracticeKindIn(vs ...PracticeKind) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldPracticeKind, vs...))
}

// PracticeKindNotIn applies the NotIn predicate on the "practice_kind" field.
func PracticeKindNotIn(vs ...PracticeKind) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldPracticeKind, vs...))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v int) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLTE(FieldDurationSeconds, v))
}

// FeedbackEQ applies the EQ predicate on the "feedback" field.
func FeedbackEQ(v Feedback) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldFeedback, v))
}

// FeedbackNEQ applies the NEQ predicate on the "feedback" field.
func FeedbackNEQ(v Feedback) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldFeedback, v))
}

// FeedbackIn applies the In predicate on the "feedback" field.
func FeedbackIn(vs ...Feedback) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldFeedback, vs...))
}

// FeedbackNotIn applies the NotIn predicate on the "feedback" field.
func FeedbackNotIn(vs ...Feedback) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldFeedback, vs...))
}

// FeedbackIsNil applies the IsNil predicate on the "feedback" field.
func FeedbackIsNil() predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIsNull(FieldFeedback))
}

// FeedbackNotNil applies the NotNil predicate on the "feedback" field.
func FeedbackNotNil() predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotNull(FieldFeedback))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLTE(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecoveryPracticeSession) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecoveryPracticeSession) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecoveryPracticeSession) predicate.RecoveryPracticeSession {
	return predicate.RecoveryPracticeSession(sql.NotPredicates(p))
}
